/*
 * Copyright (C) 2026 DevEmperor (Dictate)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

package dev.patrickgold.florisboard.ime.nlp.latin

/**
 * When a touch-decoded correction may replace what was typed **without being asked** (issues #242, #295).
 *
 * The strip always offers every candidate; this decides only the silent swap, which is the one thing a
 * keyboard does that the user did not ask for and may not notice. Three populations pull against each
 * other and a rule is only ever judged on all of them at once:
 *
 *  - a genuine mis-tap, which must be fixed — the point of autocorrect;
 *  - a correctly typed word the dictionary happens not to know (a name, a foreign word, jargon), which
 *    must be left alone, because silently rewriting it is the failure people remember;
 *  - a mis-tap swapped for a *third* word, neither typed nor meant, which is worse than no correction.
 *
 * The evidence separating them is where the fingers landed. [TouchBeamDecoder] reports the *excess*
 * squared distance of the decoded word over the nearest-key reading, in key-width² — zero for a
 * dead-centre reading of what was typed, growing as the correction requires the taps to have been
 * further off.
 *
 * ### Why the budget is per tap and not per word
 *
 * It used to be a flat 0.8 for the whole word. Both axes are normalised by *key width*
 * ([KeyProximityInfo.normalize]), so a horizontally adjacent key sits at squared distance 1.0 — which
 * means that rule admitted a tap up to ~90 % of the way towards its neighbour but never one that landed
 * *on* the neighbour, and never a word containing two slips at all. It drew the line between a spatial
 * slip (a fat finger between two keys) and a motor slip (you knew the word, your hand went one key
 * over), and only ever fixed the first. That is what #295 reports.
 *
 * Measured by `AutocorrectEvalTest` over the shipping English dictionary, single clean neighbour hits
 * ("eill" for "will"), against German words absent from it standing in for names:
 *
 * ```
 * rule                    clean 1-key slips fixed   typo→third word   correct word broken
 * total ≤ 0.8 (was)                          0.0 %             0.2 %                0.00 %
 * mean  ≤ 0.10 per tap                       6.2 %             0.2 %                0.00 %
 * mean  ≤ 0.30 per tap                      54.0 %             2.1 %                0.47 %
 * mean  ≤ 0.50 per tap                      60.4 %             5.5 %                1.86 %
 * no gate at all                            61.2 %            10.7 %                7.38 %
 * ```
 *
 * The old numbers were not wrong, they were incomplete: the typos they were tuned on were generated by
 * perturbing tap coordinates, so the "landed squarely on the wrong key" population was absent from the
 * evaluation set by construction, and the rule that came out of it rejects exactly that population.
 * Whenever this rule is touched again, run that test and read **all three** columns.
 */
object AutoCommitGate {

    /**
     * How frequent a word a correction must be, on the dictionary's stored 128..255 scale, before it may
     * be swapped in silently. Rarer fixes are still offered as tap suggestions, so an uncommon-but-
     * intentional word (a name, jargon) is never mangled by one.
     *
     * Lives here rather than in [LatinLanguageProvider] because it is half of the same question — how
     * much has to be true before we act without being asked — and because two other places have to agree
     * with it to the digit: [WordLearningGate], which reads "a correction we would have applied" as
     * evidence that a word was mistyped, and `AutocorrectEvalTest`, which measures the pair. Three
     * copies of 170 is exactly how the #242 numbers became unreproducible.
     */
    const val MIN_FREQ = 170

    /**
     * Excess tap distance per tap (key-width²) a correction may cost and still be swapped in silently.
     *
     * Per tap rather than per word, so the rule does not get stricter simply because the word is longer:
     * several consistent near-key slips are more evidence of sloppy typing, not less.
     */
    private fun budgetPerTap(strength: AutoCorrectStrength): Float = when (strength) {
        // Indistinguishable from the old flat 0.8 in harm (0 % of correct words touched) and slightly
        // better at fixing, so nobody loses by the change of shape.
        AutoCorrectStrength.CAUTIOUS -> 0.10f
        // The knee of the curve. 0.35 would fix another 4 pp of slips and double every harm column.
        AutoCorrectStrength.BALANCED -> 0.30f
        // Within a percentage point of everything the decoder can do; past here the remaining gains cost
        // several times their weight in wrongly rewritten words.
        AutoCorrectStrength.AGGRESSIVE -> 0.50f
    }

    /**
     * True when a correction costing [totalCost] over [tapCount] taps may be swapped in silently.
     */
    fun allows(totalCost: Float, tapCount: Int, strength: AutoCorrectStrength): Boolean {
        if (tapCount <= 0) return false
        return totalCost <= budgetPerTap(strength) * tapCount
    }
}
