/*
 * Copyright (C) 2026 DevEmperor (Dictate)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

package dev.patrickgold.florisboard.ime.media.emoji

import android.content.Context
import dev.patrickgold.florisboard.lib.FlorisLocale
import io.github.reactivecircus.cache4k.Cache
import org.florisboard.lib.android.bufferedReader

/** The searchable text of one emoji: its CLDR name plus the keywords listed for it. */
data class EmojiAnnotation(val name: String, val keywords: List<String>)

/**
 * The per-language emoji names and keywords behind the emoji search and the inline emoji suggestions
 * (issue #274).
 *
 * These are kept apart from the emoji *inventory* ([EmojiData], `root.txt`): the inventory says which
 * emojis exist, in which category and with which skin-tone variants, and is the same for everyone; the
 * annotations say what they are called, and differ per language. Before #274 the two were fused into one
 * file per language, which meant only the six languages that had such a file (de/en/es/fr/it/pt) could
 * be searched at all — the other 49 keyboard languages fell back to `root.txt`, whose lines carry no text
 * whatsoever (`😀;;`), so every query came up empty.
 *
 * Files are generated by `tools/emoji-annotations/generate.py` from Unicode CLDR.
 */
object EmojiAnnotations {
    private const val AssetDir = "ime/media/emoji/annotations"

    /** The language whose annotations are always loaded as a second index, so English terms work anywhere. */
    const val FallbackLanguage = "en"

    /**
     * Android's [java.util.Locale] still reports the pre-1989 ISO codes, so a Hebrew subtype arrives here
     * as `iw` and an Indonesian one as `in`. The assets are named after the modern codes.
     */
    private val LanguageAliases = mapOf("iw" to "he", "in" to "id", "ji" to "yi")

    private val cache = Cache.Builder<String, Map<String, EmojiAnnotation>>().build()

    @Volatile
    private var availableLanguages: Set<String>? = null

    /** The asset language code for [locale], which may or may not have a file — see [get]. */
    fun assetLanguage(locale: FlorisLocale): String {
        val language = locale.language.lowercase()
        return LanguageAliases[language] ?: language
    }

    /**
     * The annotations for [language], or an empty map when nothing is shipped for it. Reads from the
     * assets on first use and caches afterwards; call from a background dispatcher.
     */
    suspend fun get(context: Context, language: String): Map<String, EmojiAnnotation> {
        if (language !in languagesOf(context)) return emptyMap()
        return cache.get(language) { load(context, language) }
    }

    private fun languagesOf(context: Context): Set<String> {
        availableLanguages?.let { return it }
        val languages = runCatching {
            context.assets.list(AssetDir)!!.filter { it.endsWith(".txt") }.map { it.dropLast(".txt".length) }
        }.getOrDefault(emptyList()).toSet()
        availableLanguages = languages
        return languages
    }

    private fun load(context: Context, language: String): Map<String, EmojiAnnotation> {
        return runCatching {
            context.assets.bufferedReader("$AssetDir/$language.txt").useLines { parse(it) }
        }.getOrDefault(emptyMap())
    }

    /**
     * Parses `emoji;name;keyword|keyword` lines. Split out from the asset loading so the search can be
     * tested against the real shipped files on the JVM (see `EmojiSearchEngineTest`).
     */
    fun parse(lines: Sequence<String>): Map<String, EmojiAnnotation> {
        val annotations = HashMap<String, EmojiAnnotation>(2048)
        for (line in lines) {
            val fields = line.split(';')
            if (fields.size != 3) continue
            val value = fields[0]
            if (value.isEmpty()) continue
            val keywords = fields[2].split('|').filter { it.isNotEmpty() }
            annotations[value] = EmojiAnnotation(fields[1], keywords)
        }
        return annotations
    }
}
