/*
 * Copyright (C) 2026 DevEmperor (Dictate)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

package dev.patrickgold.florisboard.app.settings.search

import androidx.annotation.StringRes
import dev.patrickgold.florisboard.R
import dev.patrickgold.florisboard.app.Routes

/**
 * One searchable settings entry (issue #187). GENERATED from the settings screens by
 * scripts/gen_settings_search_index — do not curate by hand; rerun the generator when settings
 * change so the search stays complete. Each entry maps a localized [titleRes] to the [route]
 * that shows it, with [sectionRes] (the screen) and optional [parentRes] forming the breadcrumb.
 * When [anchor] is set the destination row is tagged with Modifier.settingsSearchAnchor and the
 * result scrolls to + highlights it; otherwise it lands on the screen.
 */
data class SettingsSearchEntry(
    @StringRes val titleRes: Int,
    @StringRes val sectionRes: Int,
    val route: Any,
    @StringRes val parentRes: Int? = null,
    val anchor: String? = null,
)

object SettingsSearchIndex {
    val entries: List<SettingsSearchEntry> = listOf(
        SettingsSearchEntry(R.string.about__title, R.string.about__title, Routes.Settings.About),
        SettingsSearchEntry(R.string.backup_and_restore__back_up__title, R.string.backup_and_restore__back_up__title, Routes.Settings.Backup, parentRes = R.string.settings__other__title),
        SettingsSearchEntry(R.string.settings__other__title, R.string.settings__other__title, Routes.Settings.Other),
        SettingsSearchEntry(R.string.physical_keyboard__title, R.string.physical_keyboard__title, Routes.Settings.PhysicalKeyboard, parentRes = R.string.settings__other__title),
        SettingsSearchEntry(R.string.backup_and_restore__restore__title, R.string.backup_and_restore__restore__title, Routes.Settings.Restore, parentRes = R.string.settings__other__title),
        SettingsSearchEntry(R.string.settings__clipboard__title, R.string.settings__clipboard__title, Routes.Settings.Clipboard),
        SettingsSearchEntry(R.string.dictate__floating_button_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__history_title, R.string.dictate__history_title, Routes.Settings.DictateHistory, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__languages_title, R.string.dictate__languages_title, Routes.Settings.DictateLanguages, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__mappings_title, R.string.dictate__mappings_title, Routes.Settings.DictateMappings, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__prompt_library_title, R.string.dictate__prompt_library_title, Routes.Settings.DictatePromptLibrary, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__providers_title, R.string.dictate__providers_title, Routes.Settings.DictateProviders, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__proxy_title, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__rewording_title, R.string.dictate__rewording_title, Routes.Settings.DictateRewording, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__title, R.string.dictate__title, Routes.Settings.Dictate),
        SettingsSearchEntry(R.string.dictate__formatting_title, R.string.dictate__formatting_title, Routes.Settings.DictateFormatting, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__recording_group, R.string.dictate__recording_group, Routes.Settings.DictateRecording, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__output_group, R.string.dictate__output_group, Routes.Settings.DictateOutput, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__layout_title, R.string.dictate__layout_title, Routes.Settings.DictateLayout, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__stats_title, R.string.dictate__stats_title, Routes.Settings.DictateStats, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__wear_title, R.string.dictate__wear_title, Routes.Settings.DictateWear, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.settings__dictionary__title, R.string.settings__dictionary__title, Routes.Settings.Dictionary),
        SettingsSearchEntry(R.string.settings__gestures__title, R.string.settings__gestures__title, Routes.Settings.Gestures),
        SettingsSearchEntry(R.string.settings__input_feedback__title, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title),
        SettingsSearchEntry(R.string.settings__keyboard__title, R.string.settings__keyboard__title, Routes.Settings.Keyboard),
        SettingsSearchEntry(R.string.settings__localization__title, R.string.settings__localization__title, Routes.Settings.Localization),
        SettingsSearchEntry(R.string.settings__media__title, R.string.settings__media__title, Routes.Settings.Media),
        SettingsSearchEntry(R.string.settings__smartbar__title, R.string.settings__smartbar__title, Routes.Settings.Smartbar),
        SettingsSearchEntry(R.string.settings__theme__title, R.string.settings__theme__title, Routes.Settings.Theme),
        SettingsSearchEntry(R.string.settings__typing__title, R.string.settings__typing__title, Routes.Settings.Typing),
        SettingsSearchEntry(R.string.about__version__title, R.string.about__title, Routes.Settings.About, anchor = "about__version__title"),
        SettingsSearchEntry(R.string.about__whats_new__title, R.string.about__title, Routes.Settings.About, anchor = "about__whats_new__title"),
        SettingsSearchEntry(R.string.about__changelog__title, R.string.about__title, Routes.Settings.About, anchor = "about__changelog__title"),
        SettingsSearchEntry(R.string.about__repository__title, R.string.about__title, Routes.Settings.About, anchor = "about__repository__title"),
        SettingsSearchEntry(R.string.about__based_on_floris__title, R.string.about__title, Routes.Settings.About, anchor = "about__based_on_floris__title"),
        SettingsSearchEntry(R.string.about__feedback__title, R.string.about__title, Routes.Settings.About, anchor = "about__feedback__title"),
        SettingsSearchEntry(R.string.about__privacy_policy__title, R.string.about__title, Routes.Settings.About, anchor = "about__privacy_policy__title"),
        SettingsSearchEntry(R.string.about__project_license__title, R.string.about__title, Routes.Settings.About, anchor = "about__project_license__title"),
        SettingsSearchEntry(R.string.pref__other__settings_theme__label, R.string.settings__other__title, Routes.Settings.Other, anchor = "pref__other__settings_theme__label"),
        SettingsSearchEntry(R.string.pref__other__settings_accent_color__label, R.string.settings__other__title, Routes.Settings.Other, anchor = "pref__other__settings_accent_color__label"),
        SettingsSearchEntry(R.string.pref__other__settings_language__label, R.string.settings__other__title, Routes.Settings.Other, anchor = "pref__other__settings_language__label"),
        SettingsSearchEntry(R.string.pref__other__show_app_icon__label, R.string.settings__other__title, Routes.Settings.Other, anchor = "pref__other__show_app_icon__label"),
        SettingsSearchEntry(R.string.physical_keyboard__title, R.string.settings__other__title, Routes.Settings.Other, anchor = "physical_keyboard__title"),
        SettingsSearchEntry(R.string.devtools__title, R.string.settings__other__title, Routes.Settings.Other, anchor = "devtools__title"),
        SettingsSearchEntry(R.string.backup_and_restore__title, R.string.settings__other__title, Routes.Settings.Other),
        SettingsSearchEntry(R.string.backup_and_restore__back_up__title, R.string.settings__other__title, Routes.Settings.Other, anchor = "backup_and_restore__back_up__title"),
        SettingsSearchEntry(R.string.backup_and_restore__restore__title, R.string.settings__other__title, Routes.Settings.Other, anchor = "backup_and_restore__restore__title"),
        SettingsSearchEntry(R.string.physical_keyboard__system_settings__title, R.string.physical_keyboard__title, Routes.Settings.PhysicalKeyboard, parentRes = R.string.settings__other__title, anchor = "physical_keyboard__system_settings__title"),
        SettingsSearchEntry(R.string.physical_keyboard__show_on_screen_keyboard__title, R.string.physical_keyboard__title, Routes.Settings.PhysicalKeyboard, parentRes = R.string.settings__other__title, anchor = "physical_keyboard__show_on_screen_keyboard__title"),
        SettingsSearchEntry(R.string.pref__clipboard__use_internal_clipboard__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__use_internal_clipboard__label"),
        SettingsSearchEntry(R.string.pref__clipboard__sync_from_system_clipboard__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__sync_from_system_clipboard__label"),
        SettingsSearchEntry(R.string.pref__clipboard__sync_to_system_clipboard__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__sync_to_system_clipboard__label"),
        SettingsSearchEntry(R.string.pref__clipboard__group_clipboard_suggestion__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard),
        SettingsSearchEntry(R.string.pref__clipboard__suggestion_enabled__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__suggestion_enabled__label"),
        SettingsSearchEntry(R.string.pref__clipboard__suggestion_timeout__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__suggestion_timeout__label"),
        SettingsSearchEntry(R.string.pref__clipboard__group_clipboard_history__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard),
        SettingsSearchEntry(R.string.pref__clipboard__enable_clipboard_history__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__enable_clipboard_history__label"),
        SettingsSearchEntry(R.string.pref__clipboard__num_history_grid_columns__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__num_history_grid_columns__label"),
        SettingsSearchEntry(R.string.pref__clipboard__clean_up_old__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__clean_up_old__label"),
        SettingsSearchEntry(R.string.pref__clipboard__clean_up_after__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__clean_up_after__label"),
        SettingsSearchEntry(R.string.pref__clipboard__auto_clean_sensitive__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__auto_clean_sensitive__label"),
        SettingsSearchEntry(R.string.pref__clipboard__auto_clean_sensitive_after__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__auto_clean_sensitive_after__label"),
        SettingsSearchEntry(R.string.pref__clipboard__limit_history_size__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__limit_history_size__label"),
        SettingsSearchEntry(R.string.pref__clipboard__max_history_size__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__max_history_size__label"),
        SettingsSearchEntry(R.string.pref__clipboard__history_hide_on_paste__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__history_hide_on_paste__label"),
        SettingsSearchEntry(R.string.pref__clipboard__history_hide_on_next_text_field__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__history_hide_on_next_text_field__label"),
        SettingsSearchEntry(R.string.pref__clipboard__clear_primary_clip_affects_history_if_unpinned__label, R.string.settings__clipboard__title, Routes.Settings.Clipboard, anchor = "pref__clipboard__clear_primary_clip_affects_history_if_unpinned__label"),
        SettingsSearchEntry(R.string.dictate__floating_button_enable_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_enable_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_permission_group, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__floating_button_service_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_service_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_mic_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_mic_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_show_with_keyboard_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_show_with_keyboard_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_design_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_design_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_size_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_size_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_snap_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_snap_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_color_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_color_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_auto_dim_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_auto_dim_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_remember_position_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_remember_position_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_haptic_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_haptic_title"),
        SettingsSearchEntry(R.string.dictate__floating_button_undo_title, R.string.dictate__floating_button_title, Routes.Settings.DictateFloatingButton, parentRes = R.string.dictate__title, anchor = "dictate__floating_button_undo_title"),
        SettingsSearchEntry(R.string.dictate__history_enable_title, R.string.dictate__history_title, Routes.Settings.DictateHistory, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__history_audio_title, R.string.dictate__history_title, Routes.Settings.DictateHistory, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__history_retention_title, R.string.dictate__history_title, Routes.Settings.DictateHistory, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__mappings_empty_title, R.string.dictate__mappings_title, Routes.Settings.DictateMappings, parentRes = R.string.dictate__title, anchor = "dictate__mappings_empty_title"),
        SettingsSearchEntry(R.string.dictate__mappings_add, R.string.dictate__mappings_title, Routes.Settings.DictateMappings, parentRes = R.string.dictate__title, anchor = "dictate__mappings_add"),
        SettingsSearchEntry(R.string.dictate__providers_add_custom, R.string.dictate__providers_title, Routes.Settings.DictateProviders, parentRes = R.string.dictate__title, anchor = "dictate__providers_add_custom"),
        SettingsSearchEntry(R.string.dictate__providers_network_group, R.string.dictate__providers_title, Routes.Settings.DictateProviders, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__proxy_title, R.string.dictate__providers_title, Routes.Settings.DictateProviders, parentRes = R.string.dictate__title, anchor = "dictate__proxy_title"),
        SettingsSearchEntry(R.string.dictate__providers_active_rewording, R.string.dictate__providers_title, Routes.Settings.DictateProviders, parentRes = R.string.dictate__title, anchor = "dictate__providers_active_rewording"),
        SettingsSearchEntry(R.string.dictate__providers_active_transcription, R.string.dictate__providers_title, Routes.Settings.DictateProviders, parentRes = R.string.dictate__title, anchor = "dictate__providers_active_transcription"),
        SettingsSearchEntry(R.string.dictate__proxy_enabled_title, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title, anchor = "dictate__proxy_enabled_title"),
        SettingsSearchEntry(R.string.dictate__proxy_server_group, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__proxy_type_title, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title, anchor = "dictate__proxy_type_title"),
        SettingsSearchEntry(R.string.dictate__proxy_host_title, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__proxy_port_title, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__proxy_auth_group, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__proxy_username_title, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__proxy_password_title, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__security_group, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__trust_user_certs_title, R.string.dictate__proxy_title, Routes.Settings.DictateProxy, parentRes = R.string.dictate__title, anchor = "dictate__trust_user_certs_title"),
        SettingsSearchEntry(R.string.dictate__rewording_enabled_title, R.string.dictate__rewording_title, Routes.Settings.DictateRewording, parentRes = R.string.dictate__title, anchor = "dictate__rewording_enabled_title"),
        SettingsSearchEntry(R.string.dictate__prompts_layout_title, R.string.dictate__rewording_title, Routes.Settings.DictateRewording, parentRes = R.string.dictate__title, anchor = "dictate__prompts_layout_title"),
        SettingsSearchEntry(R.string.dictate__manage_prompts_title, R.string.dictate__rewording_title, Routes.Settings.DictateRewording, parentRes = R.string.dictate__title, anchor = "dictate__manage_prompts_title"),
        SettingsSearchEntry(R.string.dictate__auto_formatting_title, R.string.dictate__rewording_title, Routes.Settings.DictateRewording, parentRes = R.string.dictate__title, anchor = "dictate__auto_formatting_title"),
        SettingsSearchEntry(R.string.dictate__reasoning_effort_title, R.string.dictate__rewording_title, Routes.Settings.DictateRewording, parentRes = R.string.dictate__title, anchor = "dictate__reasoning_effort_title"),
        SettingsSearchEntry(R.string.dictate__system_prompt_title, R.string.dictate__rewording_title, Routes.Settings.DictateRewording, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__system_prompt_custom_title, R.string.dictate__rewording_title, Routes.Settings.DictateRewording, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__stats_title, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__stats_title"),
        SettingsSearchEntry(R.string.dictate__history_title, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__history_title"),
        SettingsSearchEntry(R.string.dictate__layout_title, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__layout_title"),
        SettingsSearchEntry(R.string.dictate__providers_title, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__providers_title"),
        SettingsSearchEntry(R.string.dictate__languages_title, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__languages_title"),
        SettingsSearchEntry(R.string.dictate__formatting_title, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__formatting_title"),
        SettingsSearchEntry(R.string.dictate__rewording_title, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__rewording_title"),
        SettingsSearchEntry(R.string.dictate__recording_group, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__recording_group"),
        SettingsSearchEntry(R.string.dictate__output_group, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__output_group"),
        SettingsSearchEntry(R.string.dictate__floating_button_enable_title, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__floating_button_enable_title"),
        SettingsSearchEntry(R.string.dictate__wear_title, R.string.dictate__title, Routes.Settings.Dictate, anchor = "dictate__wear_title"),
        SettingsSearchEntry(R.string.dictate__style_prompt_title, R.string.dictate__formatting_title, Routes.Settings.DictateFormatting, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__style_prompt_custom_title, R.string.dictate__formatting_title, Routes.Settings.DictateFormatting, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__custom_words_title, R.string.dictate__formatting_title, Routes.Settings.DictateFormatting, parentRes = R.string.dictate__title),
        SettingsSearchEntry(R.string.dictate__mappings_title, R.string.dictate__formatting_title, Routes.Settings.DictateFormatting, parentRes = R.string.dictate__title, anchor = "dictate__mappings_title"),
        SettingsSearchEntry(R.string.dictate__realtime_title, R.string.dictate__recording_group, Routes.Settings.DictateRecording, parentRes = R.string.dictate__title, anchor = "dictate__realtime_title"),
        SettingsSearchEntry(R.string.dictate__longform_title, R.string.dictate__recording_group, Routes.Settings.DictateRecording, parentRes = R.string.dictate__title, anchor = "dictate__longform_title"),
        SettingsSearchEntry(R.string.dictate__audio_focus_title, R.string.dictate__recording_group, Routes.Settings.DictateRecording, parentRes = R.string.dictate__title, anchor = "dictate__audio_focus_title"),
        SettingsSearchEntry(R.string.dictate__bluetooth_mic_title, R.string.dictate__recording_group, Routes.Settings.DictateRecording, parentRes = R.string.dictate__title, anchor = "dictate__bluetooth_mic_title"),
        SettingsSearchEntry(R.string.dictate__audio_source_title, R.string.dictate__recording_group, Routes.Settings.DictateRecording, parentRes = R.string.dictate__title, anchor = "dictate__audio_source_title"),
        SettingsSearchEntry(R.string.dictate__keep_screen_awake_title, R.string.dictate__recording_group, Routes.Settings.DictateRecording, parentRes = R.string.dictate__title, anchor = "dictate__keep_screen_awake_title"),
        SettingsSearchEntry(R.string.dictate__skip_silent_title, R.string.dictate__recording_group, Routes.Settings.DictateRecording, parentRes = R.string.dictate__title, anchor = "dictate__skip_silent_title"),
        SettingsSearchEntry(R.string.dictate__instant_recording_title, R.string.dictate__recording_group, Routes.Settings.DictateRecording, parentRes = R.string.dictate__title, anchor = "dictate__instant_recording_title"),
        SettingsSearchEntry(R.string.dictate__instant_recording_skip_numeric_title, R.string.dictate__recording_group, Routes.Settings.DictateRecording, parentRes = R.string.dictate__title, anchor = "dictate__instant_recording_skip_numeric_title"),
        SettingsSearchEntry(R.string.dictate__auto_enter_title, R.string.dictate__output_group, Routes.Settings.DictateOutput, parentRes = R.string.dictate__title, anchor = "dictate__auto_enter_title"),
        SettingsSearchEntry(R.string.dictate__instant_output_title, R.string.dictate__output_group, Routes.Settings.DictateOutput, parentRes = R.string.dictate__title, anchor = "dictate__instant_output_title"),
        SettingsSearchEntry(R.string.dictate__output_speed_title, R.string.dictate__output_group, Routes.Settings.DictateOutput, parentRes = R.string.dictate__title, anchor = "dictate__output_speed_title"),
        SettingsSearchEntry(R.string.dictate__resend_button_title, R.string.dictate__output_group, Routes.Settings.DictateOutput, parentRes = R.string.dictate__title, anchor = "dictate__resend_button_title"),
        SettingsSearchEntry(R.string.dictate__haptic_feedback_title, R.string.dictate__output_group, Routes.Settings.DictateOutput, parentRes = R.string.dictate__title, anchor = "dictate__haptic_feedback_title"),
        SettingsSearchEntry(R.string.dictate__remember_last_dictation_title, R.string.dictate__output_group, Routes.Settings.DictateOutput, parentRes = R.string.dictate__title, anchor = "dictate__remember_last_dictation_title"),
        SettingsSearchEntry(R.string.dictate__legacy_layout_title, R.string.dictate__layout_title, Routes.Settings.DictateLayout, parentRes = R.string.dictate__title, anchor = "dictate__legacy_layout_title"),
        SettingsSearchEntry(R.string.dictate__legacy_prompt_rows_title, R.string.dictate__layout_title, Routes.Settings.DictateLayout, parentRes = R.string.dictate__title, anchor = "dictate__legacy_prompt_rows_title"),
        SettingsSearchEntry(R.string.dictate__wear_install_title, R.string.dictate__wear_title, Routes.Settings.DictateWear, parentRes = R.string.dictate__title, anchor = "dictate__wear_install_title"),
        SettingsSearchEntry(R.string.dictate__wear_standalone_title, R.string.dictate__wear_title, Routes.Settings.DictateWear, parentRes = R.string.dictate__title, anchor = "dictate__wear_standalone_title"),
        SettingsSearchEntry(R.string.dictate__wear_auto_rewording_title, R.string.dictate__wear_title, Routes.Settings.DictateWear, parentRes = R.string.dictate__title, anchor = "dictate__wear_auto_rewording_title"),
        SettingsSearchEntry(R.string.pref__dictionary__enable_system_user_dictionary__label, R.string.settings__dictionary__title, Routes.Settings.Dictionary, anchor = "pref__dictionary__enable_system_user_dictionary__label"),
        SettingsSearchEntry(R.string.pref__dictionary__manage_system_user_dictionary__label, R.string.settings__dictionary__title, Routes.Settings.Dictionary, anchor = "pref__dictionary__manage_system_user_dictionary__label"),
        SettingsSearchEntry(R.string.pref__dictionary__enable_internal_user_dictionary__label, R.string.settings__dictionary__title, Routes.Settings.Dictionary, anchor = "pref__dictionary__enable_internal_user_dictionary__label"),
        SettingsSearchEntry(R.string.pref__dictionary__manage_floris_user_dictionary__label, R.string.settings__dictionary__title, Routes.Settings.Dictionary, anchor = "pref__dictionary__manage_floris_user_dictionary__label"),
        SettingsSearchEntry(R.string.pref__glide__enabled__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__glide__enabled__label"),
        SettingsSearchEntry(R.string.pref__glide__show_trail__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__glide__show_trail__label"),
        SettingsSearchEntry(R.string.pref__glide_trail_fade_duration, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__glide_trail_fade_duration"),
        SettingsSearchEntry(R.string.pref__glide__show_preview, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__glide__show_preview"),
        SettingsSearchEntry(R.string.pref__glide_preview_refresh_delay, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__glide_preview_refresh_delay"),
        SettingsSearchEntry(R.string.pref__glide__immediate_backspace_deletes_word__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__glide__immediate_backspace_deletes_word__label"),
        SettingsSearchEntry(R.string.pref__gestures__general_title, R.string.settings__gestures__title, Routes.Settings.Gestures),
        SettingsSearchEntry(R.string.pref__gestures__swipe_up__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__swipe_up__label"),
        SettingsSearchEntry(R.string.pref__gestures__swipe_down__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__swipe_down__label"),
        SettingsSearchEntry(R.string.pref__gestures__swipe_left__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__swipe_left__label"),
        SettingsSearchEntry(R.string.pref__gestures__swipe_right__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__swipe_right__label"),
        SettingsSearchEntry(R.string.pref__gestures__space_bar_title, R.string.settings__gestures__title, Routes.Settings.Gestures),
        SettingsSearchEntry(R.string.pref__gestures__space_bar_swipe_up__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__space_bar_swipe_up__label"),
        SettingsSearchEntry(R.string.pref__gestures__space_bar_swipe_left__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__space_bar_swipe_left__label"),
        SettingsSearchEntry(R.string.pref__gestures__space_bar_swipe_right__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__space_bar_swipe_right__label"),
        SettingsSearchEntry(R.string.pref__gestures__space_bar_long_press__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__space_bar_long_press__label"),
        SettingsSearchEntry(R.string.pref__gestures__other_title, R.string.settings__gestures__title, Routes.Settings.Gestures),
        SettingsSearchEntry(R.string.pref__gestures__delete_key_swipe_left__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__delete_key_swipe_left__label"),
        SettingsSearchEntry(R.string.pref__gestures__delete_key_long_press__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__delete_key_long_press__label"),
        SettingsSearchEntry(R.string.pref__gestures__swipe_velocity_threshold__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__swipe_velocity_threshold__label"),
        SettingsSearchEntry(R.string.pref__gestures__swipe_distance_threshold__label, R.string.settings__gestures__title, Routes.Settings.Gestures, anchor = "pref__gestures__swipe_distance_threshold__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__audio_enabled__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__audio_enabled__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__audio_volume__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__audio_volume__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__audio_feat_key_press__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__audio_feat_key_press__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__audio_feat_key_long_press__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__audio_feat_key_long_press__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__audio_feat_key_repeated_action__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__audio_feat_key_repeated_action__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__audio_feat_gesture_swipe__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__audio_feat_gesture_swipe__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__audio_feat_gesture_moving_swipe__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__audio_feat_gesture_moving_swipe__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__group_haptic__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title),
        SettingsSearchEntry(R.string.pref__input_feedback__haptic_enabled__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__haptic_enabled__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__haptic_vibration_mode__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__haptic_vibration_mode__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__haptic_vibration_duration__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__haptic_vibration_duration__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__haptic_vibration_strength__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__haptic_vibration_strength__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__haptic_feat_key_press__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__haptic_feat_key_press__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__haptic_feat_key_long_press__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__haptic_feat_key_long_press__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__haptic_feat_key_repeated_action__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__haptic_feat_key_repeated_action__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__haptic_feat_gesture_swipe__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__haptic_feat_gesture_swipe__label"),
        SettingsSearchEntry(R.string.pref__input_feedback__haptic_feat_gesture_moving_swipe__label, R.string.settings__input_feedback__title, Routes.Settings.InputFeedback, parentRes = R.string.settings__keyboard__title, anchor = "pref__input_feedback__haptic_feat_gesture_moving_swipe__label"),
        SettingsSearchEntry(R.string.pref__keyboard__number_row__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__number_row__label"),
        SettingsSearchEntry(R.string.pref__keyboard__hinted_number_row_mode__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__hinted_number_row_mode__label"),
        SettingsSearchEntry(R.string.pref__keyboard__hinted_symbols_mode__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__hinted_symbols_mode__label"),
        SettingsSearchEntry(R.string.pref__keyboard__utility_key_enabled__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__utility_key_enabled__label"),
        SettingsSearchEntry(R.string.pref__keyboard__utility_key_action__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__utility_key_action__label"),
        SettingsSearchEntry(R.string.pref__keyboard__space_bar_mode__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__space_bar_mode__label"),
        SettingsSearchEntry(R.string.pref__keyboard__capitalization_behavior__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__capitalization_behavior__label"),
        SettingsSearchEntry(R.string.pref__keyboard__font_size_multiplier__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__font_size_multiplier__label"),
        SettingsSearchEntry(R.string.pref__keyboard__incognito_indicator__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__incognito_indicator__label"),
        SettingsSearchEntry(R.string.pref__keyboard__group_layout__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard),
        SettingsSearchEntry(R.string.pref__keyboard__landscape_input_ui_mode__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__landscape_input_ui_mode__label"),
        SettingsSearchEntry(R.string.pref__keyboard__key_spacing__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__key_spacing__label"),
        SettingsSearchEntry(R.string.settings__input_feedback__title, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "settings__input_feedback__title"),
        SettingsSearchEntry(R.string.pref__keyboard__popup_enabled__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__popup_enabled__label"),
        SettingsSearchEntry(R.string.pref__keyboard__merge_hint_popups_enabled__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__merge_hint_popups_enabled__label"),
        SettingsSearchEntry(R.string.pref__keyboard__long_press_delay__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__long_press_delay__label"),
        SettingsSearchEntry(R.string.pref__keyboard__space_bar_switches_to_characters__label, R.string.settings__keyboard__title, Routes.Settings.Keyboard, anchor = "pref__keyboard__space_bar_switches_to_characters__label"),
        SettingsSearchEntry(R.string.settings__localization__display_language_names_in__label, R.string.settings__localization__title, Routes.Settings.Localization, anchor = "settings__localization__display_language_names_in__label"),
        SettingsSearchEntry(R.string.settings__localization__display_keyboard_labels_in_subtype_language, R.string.settings__localization__title, Routes.Settings.Localization, anchor = "settings__localization__display_keyboard_labels_in_subtype_language"),
        SettingsSearchEntry(R.string.settings__localization__language_pack_title, R.string.settings__localization__title, Routes.Settings.Localization, anchor = "settings__localization__language_pack_title"),
        SettingsSearchEntry(R.string.settings__localization__group_subtypes__label, R.string.settings__localization__title, Routes.Settings.Localization),
        SettingsSearchEntry(R.string.prefs__media__gif_setup__title, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__gif_setup__title"),
        SettingsSearchEntry(R.string.prefs__media__emoji_preferred_skin_tone, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_preferred_skin_tone"),
        SettingsSearchEntry(R.string.prefs__media__emoji_history__title, R.string.settings__media__title, Routes.Settings.Media),
        SettingsSearchEntry(R.string.prefs__media__emoji_history_enabled, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_history_enabled"),
        SettingsSearchEntry(R.string.prefs__media__emoji_history_pinned_update_strategy, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_history_pinned_update_strategy"),
        SettingsSearchEntry(R.string.prefs__media__emoji_history_recent_update_strategy, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_history_recent_update_strategy"),
        SettingsSearchEntry(R.string.prefs__media__emoji_history_max_size, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_history_max_size"),
        SettingsSearchEntry(R.string.prefs__media__emoji_history_pinned_reset, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_history_pinned_reset"),
        SettingsSearchEntry(R.string.prefs__media__emoji_history_reset, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_history_reset"),
        SettingsSearchEntry(R.string.prefs__media__emoji_suggestion__title, R.string.settings__media__title, Routes.Settings.Media),
        SettingsSearchEntry(R.string.prefs__media__emoji_suggestion_enabled, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_suggestion_enabled"),
        SettingsSearchEntry(R.string.prefs__media__emoji_suggestion_type, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_suggestion_type"),
        SettingsSearchEntry(R.string.prefs__media__emoji_suggestion_update_history, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_suggestion_update_history"),
        SettingsSearchEntry(R.string.prefs__media__emoji_suggestion_candidate_show_name, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_suggestion_candidate_show_name"),
        SettingsSearchEntry(R.string.prefs__media__emoji_suggestion_query_min_length, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_suggestion_query_min_length"),
        SettingsSearchEntry(R.string.prefs__media__emoji_suggestion_candidate_max_count, R.string.settings__media__title, Routes.Settings.Media, anchor = "prefs__media__emoji_suggestion_candidate_max_count"),
        SettingsSearchEntry(R.string.pref__smartbar__enabled__label, R.string.settings__smartbar__title, Routes.Settings.Smartbar, anchor = "pref__smartbar__enabled__label"),
        SettingsSearchEntry(R.string.pref__smartbar__layout__label, R.string.settings__smartbar__title, Routes.Settings.Smartbar, anchor = "pref__smartbar__layout__label"),
        SettingsSearchEntry(R.string.pref__smartbar__group_layout_specific__label, R.string.settings__smartbar__title, Routes.Settings.Smartbar),
        SettingsSearchEntry(R.string.pref__suggestion__display_mode__label, R.string.settings__smartbar__title, Routes.Settings.Smartbar, anchor = "pref__suggestion__display_mode__label"),
        SettingsSearchEntry(R.string.pref__smartbar__flip_toggles__label, R.string.settings__smartbar__title, Routes.Settings.Smartbar, anchor = "pref__smartbar__flip_toggles__label"),
        SettingsSearchEntry(R.string.pref__smartbar__shared_actions_auto_expand_collapse__label, R.string.settings__smartbar__title, Routes.Settings.Smartbar, anchor = "pref__smartbar__shared_actions_auto_expand_collapse__label"),
        SettingsSearchEntry(R.string.pref__smartbar__extended_actions_placement__label, R.string.settings__smartbar__title, Routes.Settings.Smartbar, anchor = "pref__smartbar__extended_actions_placement__label"),
        SettingsSearchEntry(R.string.pref__theme__mode__label, R.string.settings__theme__title, Routes.Settings.Theme, anchor = "pref__theme__mode__label"),
        SettingsSearchEntry(R.string.pref__theme__day, R.string.settings__theme__title, Routes.Settings.Theme, anchor = "pref__theme__day"),
        SettingsSearchEntry(R.string.pref__theme__night, R.string.settings__theme__title, Routes.Settings.Theme, anchor = "pref__theme__night"),
        SettingsSearchEntry(R.string.pref__theme__theme_accent_color__label, R.string.settings__theme__title, Routes.Settings.Theme, anchor = "pref__theme__theme_accent_color__label"),
        SettingsSearchEntry(R.string.pref__suggestion__enabled__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__suggestion__enabled__label"),
        SettingsSearchEntry(R.string.pref__suggestion__auto_correct__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__suggestion__auto_correct__label"),
        SettingsSearchEntry(R.string.pref__suggestion__multilingual_typing__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__suggestion__multilingual_typing__label"),
        SettingsSearchEntry(R.string.pref__suggestion__api30_inline_suggestions_enabled__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__suggestion__api30_inline_suggestions_enabled__label"),
        SettingsSearchEntry(R.string.pref__suggestion__incognito_mode__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__suggestion__incognito_mode__label"),
        SettingsSearchEntry(R.string.pref__correction__title, R.string.settings__typing__title, Routes.Settings.Typing),
        SettingsSearchEntry(R.string.pref__correction__auto_capitalization__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__correction__auto_capitalization__label"),
        SettingsSearchEntry(R.string.pref__correction__auto_space_punctuation__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__correction__auto_space_punctuation__label"),
        SettingsSearchEntry(R.string.pref__correction__remember_caps_lock_state__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__correction__remember_caps_lock_state__label"),
        SettingsSearchEntry(R.string.pref__correction__double_space_period__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__correction__double_space_period__label"),
        SettingsSearchEntry(R.string.pref__spelling__title, R.string.settings__typing__title, Routes.Settings.Typing),
        SettingsSearchEntry(R.string.pref__spelling__language_mode__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__spelling__language_mode__label"),
        SettingsSearchEntry(R.string.pref__spelling__use_contacts__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__spelling__use_contacts__label"),
        SettingsSearchEntry(R.string.pref__spelling__use_udm_entries__label, R.string.settings__typing__title, Routes.Settings.Typing, anchor = "pref__spelling__use_udm_entries__label"),
        SettingsSearchEntry(R.string.settings__dictionary__title, R.string.settings__typing__title, Routes.Settings.Typing),
    )
}
