/*
 * Copyright (C) 2026 DevEmperor (Dictate)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

// GENERATED by tools/bergamot/prepare_models.py from Mozilla's model registry
// (2026-09-25T01:07:04Z). Do not edit by hand; rerun the script and upload what it mirrors.

package dev.patrickgold.florisboard.dictate.translate

import dev.patrickgold.florisboard.dictate.translate.TranslationModelFile.Role

internal const val TRANSLATION_MODELS_RELEASE = "https://github.com/DevEmperor/DictateKeyboard/releases/download/translation-models-v1"

internal val TRANSLATION_LANGUAGES: List<TranslationLanguage> = listOf(
    TranslationLanguage(
        "af",
        TranslationDirection("af", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.afen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.afen.s2t.bin.gz", 2133684, 4082680, "7e8fd0a4043ae2118d9f1552037c4c40a8887d1ecc05161eb7c27dec0aa7ba41"),
            TranslationModelFile(Role.MODEL, "model.afen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.afen.intgemm.alphas.bin.gz", 23479680, 31561787, "0346a8b3e3a0d9fbe65012b80d2d56c1ce027725b4065442c7eeda635b606def"),
            TranslationModelFile(Role.VOCAB, "vocab.afen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.afen.spm.gz", 408581, 809319, "3fb78ba5b6965c131c6437a3862e20540121b5cd5b2c7e8aa1760f2e780926ed"),
        )),
        TranslationDirection("en", "af", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enaf.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enaf.s2t.bin.gz", 1667268, 3193340, "1b44bcffeed3096e7dfdbf536bed0bbe73f002590208db4d99b2351469f88489"),
            TranslationModelFile(Role.MODEL, "model.enaf.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enaf.intgemm.alphas.bin.gz", 23561122, 31561787, "42e0295b3dc0dfa933d3fe38332e5f213a75a651f0a33ceea9e825b4dace7783"),
            TranslationModelFile(Role.VOCAB, "vocab.enaf.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enaf.spm.gz", 409344, 809195, "2dfecb5a5e2182f3ee235ac612f6a259c8a77d665fdca4cb50e959ffec9cded7"),
        )),
    ),
    TranslationLanguage(
        "ar",
        TranslationDirection("ar", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.aren.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.aren.s2t.bin.gz", 2259861, 4627200, "59335a02934f19f5e9bf171de9db8b73b5e95a69dce03a7d2fe6e9e43e3f849e"),
            TranslationModelFile(Role.MODEL, "model.aren.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.aren.intgemm.alphas.bin.gz", 23224456, 31561787, "31e032a402a8463a1e19c8e355529f73c0732926b22b1eadc8bade39ecc23a80"),
            TranslationModelFile(Role.VOCAB, "vocab.aren.spm", "$TRANSLATION_MODELS_RELEASE/vocab.aren.spm.gz", 416700, 860035, "c379c52857c2f0886ae52a255ac770e5992524782ee20bb0966deca079e9595f"),
        )),
        TranslationDirection("en", "ar", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enar.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enar.s2t.bin.gz", 1639219, 3139692, "b7466406d7f5e0c493bc65dc7de221aa3e6cd7f95c6fc7dd1e73759520c937ac"),
            TranslationModelFile(Role.MODEL, "model.enar.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enar.intgemm.alphas.bin.gz", 22857819, 31561787, "88e85e33403cda6b1a529f32dc30c0977a4234285d6f8340e0d630da21b176e5"),
            TranslationModelFile(Role.VOCAB, "vocab.enar.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enar.spm.gz", 418930, 863591, "3a4b9e81c0f73ef8ed02c254b3ae99d64f8265afa54a6b838a0870bb4f9d0369"),
        )),
    ),
    TranslationLanguage(
        "bg",
        TranslationDirection("bg", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.bgen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.bgen.s2t.bin.gz", 2187053, 4355920, "54e5f362ad9d24aa33e928cf388cc7f26269304ae86f862204ae755449cc8e61"),
            TranslationModelFile(Role.MODEL, "model.bgen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.bgen.intgemm.alphas.bin.gz", 22399269, 31561787, "7a16f2855a4d046f77deaa16105338bc29ed42d6eebd8a26908ea7e1da60b736"),
            TranslationModelFile(Role.VOCAB, "vocab.bgen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.bgen.spm.gz", 434940, 922482, "405926c43e22c5eaaef6316c545dfbcf4017f492366a09b2c029921c6651b05d"),
        )),
        TranslationDirection("en", "bg", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enbg.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enbg.s2t.bin.gz", 1548577, 3075948, "622efe6dd21c6b142d87457be6d045fb18625b14dedc0ce7e875fe9ee3d5d05c"),
            TranslationModelFile(Role.MODEL, "model.enbg.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enbg.intgemm.alphas.bin.gz", 23432015, 31561787, "ae4b41190c7a0ff662fcda88a2c22fb2f0e09a8f9f5bc28632b23236e1d3ac0b"),
            TranslationModelFile(Role.VOCAB, "vocab.enbg.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enbg.spm.gz", 434940, 922482, "6647c72913621a7edbf04923573a7967092f29d3f3b35f570b7edd076e2437c2"),
        )),
    ),
    TranslationLanguage(
        "bn",
        TranslationDirection("bn", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.bnen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.bnen.s2t.bin.gz", 2264284, 4793596, "8c4bf16a8a83f6c21a25f39eb1b1f935cb60e21a5afaa83b1e0fcd40e0180a82"),
            TranslationModelFile(Role.MODEL, "model.bnen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.bnen.intgemm.alphas.bin.gz", 12665857, 17141051, "1a2e5bfd8d75c8cddd6a802f9e2a2a82b626ec88fbcb5575e242a306bc1ebe9b"),
            TranslationModelFile(Role.VOCAB, "vocab.bnen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.bnen.spm.gz", 437571, 981300, "11660de65a60243f944dc7a099beaeab8f061d8526aed15c476416a6dd906793"),
        )),
        TranslationDirection("en", "bn", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enbn.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enbn.s2t.bin.gz", 1607697, 3207488, "912cd83ad6b07d9df92b073f1bcbd49303c2b2ddba0b4d29d85b66b6f0b67f95"),
            TranslationModelFile(Role.MODEL, "model.enbn.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enbn.intgemm.alphas.bin.gz", 12821521, 17141051, "df17fb759afe3172d4ea0ded8abbe5b74d945a8acb0cac99e8fd55f92f926d8b"),
            TranslationModelFile(Role.VOCAB, "vocab.enbn.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enbn.spm.gz", 437373, 981226, "96e8b61918f5307f368937ff59f4cfea0bb7eb816e34f81bea6ac09399ee4b30"),
        )),
    ),
    TranslationLanguage(
        "ca",
        TranslationDirection("ca", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.caen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.caen.s2t.bin.gz", 2257590, 4359552, "3f8c8c81ab110e3dd77bca0c1b39e66e352cdf3da95e5275a148478cf81942f4"),
            TranslationModelFile(Role.MODEL, "model.caen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.caen.intgemm.alphas.bin.gz", 22787743, 31561787, "7b27f998a05917ca3f854d1ac45e70f8b23119d3b132114b57cbaaafe6cc63d0"),
            TranslationModelFile(Role.VOCAB, "vocab.caen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.caen.spm.gz", 409662, 810273, "93398a42647c0af477281e9c2156f494641c18191800204b2516360ca1abb111"),
        )),
        TranslationDirection("en", "ca", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enca.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enca.s2t.bin.gz", 2085904, 4344092, "ee1445b2517bb5fc13312890d0154e847279e0a780d72ee5f3b5b13867ab84ce"),
            TranslationModelFile(Role.MODEL, "model.enca.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enca.intgemm.alphas.bin.gz", 23174479, 31561787, "78c40c9f71e3456021d7aadd4cfd4e0b3665bd202e31eb0da09d1b835503b28d"),
            TranslationModelFile(Role.VOCAB, "vocab.enca.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enca.spm.gz", 409866, 810653, "873d5c52e9ff336a8dd24695de1ef4293c82f71e8e8a1c5370791292192c35d9"),
        )),
    ),
    TranslationLanguage(
        "cs",
        TranslationDirection("cs", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.csen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.csen.s2t.bin.gz", 2493702, 4990588, "ab2d7fdd47fab92bf27b80cdb32d5ec6820f784127e7c0d080ffe8005a6b58cc"),
            TranslationModelFile(Role.MODEL, "model.csen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.csen.intgemm.alphas.bin.gz", 22830296, 31561787, "b3a43eedf9ed1dc250ea44aaea3740c9e032a606eaae0e80ae5702f418b056f3"),
            TranslationModelFile(Role.VOCAB, "vocab.csen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.csen.spm.gz", 412691, 815154, "6c35be6ead9eddbc2c2bda2a059c9cb91690314c15139b347d8e1f79a318f973"),
        )),
        TranslationDirection("en", "cs", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.encs.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.encs.s2t.bin.gz", 1896925, 3572436, "e5e54ed7488b5beafef1947788534b6e3919ebe658d0a432ef00962bac1769ff"),
            TranslationModelFile(Role.MODEL, "model.encs.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.encs.intgemm.alphas.bin.gz", 23192301, 31561787, "363519c1560786f8c9c85737431ec61c770623b1ee99dff7b154019ab202d8d9"),
            TranslationModelFile(Role.VOCAB, "vocab.encs.spm", "$TRANSLATION_MODELS_RELEASE/vocab.encs.spm.gz", 412691, 815154, "842c1396415257eb864d1ce4722eece82f024a23ecdc4e1be5defcdf6b6d2c0e"),
        )),
    ),
    TranslationLanguage(
        "da",
        TranslationDirection("da", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.daen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.daen.s2t.bin.gz", 2170970, 4489412, "ab1656c067409541b3bdffd2878f3201ba51de70a42520da870de687ed37c0b8"),
            TranslationModelFile(Role.MODEL, "model.daen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.daen.intgemm.alphas.bin.gz", 12525769, 17141051, "483abf1ae01a79f3231f22b5c0aa44b8696fa0d5527801c7588a07ae2700836e"),
            TranslationModelFile(Role.VOCAB, "vocab.daen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.daen.spm.gz", 399344, 796018, "b0055ebdf5291b666c33f15ef41abba6820c09703fff7f6b1fc2726fa10ede73"),
        )),
        TranslationDirection("en", "da", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enda.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enda.s2t.bin.gz", 1582768, 3864788, "c3d79a2ba450f92ec7cb4f38a39d7b3e157417f6fb60d060fa6f3f2c05d31de9"),
            TranslationModelFile(Role.MODEL, "model.enda.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enda.intgemm.alphas.bin.gz", 12723889, 17141051, "5afaea5545cfc759ad1d2c320d17606e95efcfb0c6e4d9019903ee4c00b8091f"),
            TranslationModelFile(Role.VOCAB, "vocab.enda.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enda.spm.gz", 398818, 795349, "2d9ff33c0adfc4a137ba0cc51f64e7886ae92dbd53fd718cce30fb6ec9aa33c2"),
        )),
    ),
    TranslationLanguage(
        "de",
        TranslationDirection("de", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.deen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.deen.s2t.bin.gz", 2626658, 4945796, "231e9caf62e0e867775d5f4c1f4cfae21e37c70d9bf2bd628fa468aeeb2ba869"),
            TranslationModelFile(Role.MODEL, "model.deen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.deen.intgemm.alphas.bin.gz", 22403755, 31561787, "38b245bcfc23f6d61fd98a187436ea1320a38f41896df411b103df3e83f51681"),
            TranslationModelFile(Role.VOCAB, "vocab.deen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.deen.spm.gz", 413879, 810073, "88dcd7fdbf20dc60837ce837244d0d55b20f7079f2cbd2ba8e63530632028310"),
        )),
        TranslationDirection("en", "de", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.ende.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.ende.s2t.bin.gz", 2314750, 4347672, "0370d79cda6fed5dfa8f9b2a0009459bd2766893825bb5b8b5114169d18da6c4"),
            TranslationModelFile(Role.MODEL, "model.ende.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.ende.intgemm.alphas.bin.gz", 22992073, 31561787, "e3a74458faba3ab2752ed8355c5e3979f13395279c8fc1bd3f54a3c2316e4975"),
            TranslationModelFile(Role.VOCAB, "vocab.ende.spm", "$TRANSLATION_MODELS_RELEASE/vocab.ende.spm.gz", 413879, 810073, "3b2ddbfac73f994f151a8994447d6b3d41ab0d3435da56f79c233f34d03e45c2"),
        )),
    ),
    TranslationLanguage(
        "el",
        TranslationDirection("el", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.elen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.elen.s2t.bin.gz", 1851246, 4295860, "eef43a7471758df2a43f505e5670f3509093ab6a0742a3110d873047cc0913af"),
            TranslationModelFile(Role.MODEL, "model.elen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.elen.intgemm.alphas.bin.gz", 12696541, 17141051, "3a1d8af5cdf9ab4ace92dc988f496eb5d4e5c905834aa254b688c95a0fd5863f"),
            TranslationModelFile(Role.VOCAB, "vocab.elen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.elen.spm.gz", 419174, 894960, "076f2f01f855b08870083c569bd264d22e5bee3c35d30a1d16f7c42ae0bfc50f"),
        )),
        TranslationDirection("en", "el", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enel.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enel.s2t.bin.gz", 1352643, 2856724, "e03309c345e05bf23956a9e3d637d65cea1e75f323dbcb958c51cfb58397306a"),
            TranslationModelFile(Role.MODEL, "model.enel.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enel.intgemm.alphas.bin.gz", 12808027, 17141051, "cfe3af93ed24be241638ff246b716855bfcb7273b7a57c4fb6ac73bbe660479a"),
            TranslationModelFile(Role.VOCAB, "vocab.enel.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enel.spm.gz", 419275, 896168, "bfbab13d4ff67e08e98e9203ab0d7efd02fa143614b3244da1902baf47793b26"),
        )),
    ),
    TranslationLanguage(
        "es",
        TranslationDirection("es", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.esen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.esen.s2t.bin.gz", 2543246, 4636248, "3d7856bfa3b12804bdc80f12fd828fd9062c462113ab73fbf87c5c3b68420813"),
            TranslationModelFile(Role.MODEL, "model.esen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.esen.intgemm.alphas.bin.gz", 23288494, 31561787, "54247f1e057180bca1d404dfd5c12836f65bc96cef7af98e59e55acb8bd093b1"),
            TranslationModelFile(Role.VOCAB, "vocab.esen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.esen.spm.gz", 409312, 816054, "1658b529b8858cf2e1e8cef2c4e2d69654d77b5f714ac52205864b336dfeb3ee"),
        )),
        TranslationDirection("en", "es", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enes.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enes.s2t.bin.gz", 2265250, 4198436, "37a067966f28ff0ba430fddb7412bc5b07afa2cd2fd5a46d9ad74045a1a06380"),
            TranslationModelFile(Role.MODEL, "model.enes.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enes.intgemm.alphas.bin.gz", 22698792, 31561787, "fe4025fde24a4d5f80533cfb7acd53d0eb7f194dfc2d8f427f0d4563cfb6ac06"),
            TranslationModelFile(Role.VOCAB, "vocab.enes.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enes.spm.gz", 409312, 816054, "ae2760c04bc6eb5362b16e5c2f145c376bb04bac421c33ba3c0766805e6f03b3"),
        )),
    ),
    TranslationLanguage(
        "et",
        TranslationDirection("et", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.eten.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.eten.s2t.bin.gz", 2321326, 4625968, "7e4df142ad4f27d18e3e7f38efb9f39ec1f8c110e6ef7633f6b284f00ecb1337"),
            TranslationModelFile(Role.MODEL, "model.eten.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.eten.intgemm.alphas.bin.gz", 22785077, 31561787, "66d74dbc32b4ed8fe867fb466a7c4b8aaf7b13f66e4a8b7180b27b931fcb69b4"),
            TranslationModelFile(Role.VOCAB, "vocab.eten.spm", "$TRANSLATION_MODELS_RELEASE/vocab.eten.spm.gz", 414262, 817574, "ae1edb16d6c7c7b9591f128038a98c4555ea3dfb9c0abfd80ee3bb4caebf8cae"),
        )),
        TranslationDirection("en", "et", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enet.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enet.s2t.bin.gz", 1865410, 3488368, "9b1fd077aa1b6f77193caef680dfbfb21a783750d6bc94903c0ae9e83bc8d683"),
            TranslationModelFile(Role.MODEL, "model.enet.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enet.intgemm.alphas.bin.gz", 22951751, 31561787, "f65765a60a5ad5e0db457ee7aca053bd50fc5653b3d1edf3e3d11282db026580"),
            TranslationModelFile(Role.VOCAB, "vocab.enet.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enet.spm.gz", 414262, 817574, "4fb13bc455726ffb3434a68bd210a83231198c9a62a059debf804821428044c4"),
        )),
    ),
    TranslationLanguage(
        "eu",
        TranslationDirection("eu", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.euen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.euen.s2t.bin.gz", 1896953, 3738856, "7db2a5118755783785d5d8c7abbd17fbb355dadd4133139ddf74a7c50dac6f4e"),
            TranslationModelFile(Role.MODEL, "model.euen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.euen.intgemm.alphas.bin.gz", 23241057, 31561787, "8786171cbe14aa01689d1bf3c276ec1f4ad4072ef42aad9a4b40f5b22366c147"),
            TranslationModelFile(Role.VOCAB, "vocab.euen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.euen.spm.gz", 412669, 826064, "374721d13320d60ba9087d75030d8aa18f94dcaf102ac94251ba9e520600277a"),
        )),
        TranslationDirection("en", "eu", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.eneu.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.eneu.s2t.bin.gz", 1638880, 3149580, "801983dc96c65194ca5f4b4091b6b94a995695b274eb7712f9dc60676f1e59aa"),
            TranslationModelFile(Role.MODEL, "model.eneu.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.eneu.intgemm.alphas.bin.gz", 23068167, 31561787, "bb541caf59ff3abd99ccd6270640b47f07831b1615355033cb94d841b5ea0a26"),
            TranslationModelFile(Role.VOCAB, "vocab.eneu.spm", "$TRANSLATION_MODELS_RELEASE/vocab.eneu.spm.gz", 409774, 820820, "ff4a327aeae0d1fac1b2a331980e9e518b8e0778ce62eb557fc6d997101321be"),
        )),
    ),
    TranslationLanguage(
        "fa",
        TranslationDirection("fa", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.faen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.faen.s2t.bin.gz", 1939291, 3896420, "3ff28e45fbe6ef1742d65f525fda0c0be2255cb04cffdcfb0f9e1c21635dde90"),
            TranslationModelFile(Role.MODEL, "model.faen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.faen.intgemm.alphas.bin.gz", 13071390, 17141051, "b72e5c310d36cc5f92f143f44bd3d5ce645c1ba71668ec016f4a947e39880a2b"),
            TranslationModelFile(Role.VOCAB, "vocab.faen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.faen.spm.gz", 416123, 843153, "23252b82bf5299f6e26925b0e40f0f3bf35d51c954e5d4402cc4072c62db6c24"),
        )),
        TranslationDirection("en", "fa", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enfa.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enfa.s2t.bin.gz", 1728367, 3631332, "a5fc8b6d661f493767954c138c40b336e10aa8d2a1957ecb330face9e2fd36d2"),
            TranslationModelFile(Role.MODEL, "model.enfa.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enfa.intgemm.alphas.bin.gz", 13058508, 17141051, "9200d122bb62c7935f9c31a2d84c5503d22c0905d4f9e965743099b7c3748c8b"),
            TranslationModelFile(Role.VOCAB, "vocab.enfa.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enfa.spm.gz", 416223, 843133, "9a9961f08f3c015e8b0963d6537d931e0d3829736b9ab9766fcfaabf4f32cab4"),
        )),
    ),
    TranslationLanguage(
        "fi",
        TranslationDirection("fi", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.fien.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.fien.s2t.bin.gz", 2580517, 5195132, "cfc9a2b2feeb41593e23291962bf274ba4d5400f395cbcfa1ed1c5b6eaa098a7"),
            TranslationModelFile(Role.MODEL, "model.fien.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.fien.intgemm.alphas.bin.gz", 22935246, 31561787, "76a66ef31861fa6d3abf55f960165cb6b3dbffad8fc6371e1965dd4ec33a7bf5"),
            TranslationModelFile(Role.VOCAB, "vocab.fien.spm", "$TRANSLATION_MODELS_RELEASE/vocab.fien.spm.gz", 414280, 818770, "520424fc428c6465d64a9d48c0d14cc7bc6565a172bf9edf9220f6c62219e479"),
        )),
        TranslationDirection("en", "fi", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enfi.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enfi.s2t.bin.gz", 1875557, 3490092, "c6b670273bdac5e96c78a2dd50c70a3b93bde60af6ead06ffb9f852c9e44c023"),
            TranslationModelFile(Role.MODEL, "model.enfi.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enfi.intgemm.alphas.bin.gz", 22580027, 31561787, "e75f0b5e86b03273ac1cca68184544913a0ff6483d6f9a01defd19bf973e49cf"),
            TranslationModelFile(Role.VOCAB, "vocab.enfi.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enfi.spm.gz", 414280, 818770, "607524d7b6b8460d823c6b0e90a6593be682bc334a6f9c2c0f0d3767be66bdf9"),
        )),
    ),
    TranslationLanguage(
        "fr",
        TranslationDirection("fr", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.fren.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.fren.s2t.bin.gz", 2649934, 4824120, "395aa7767220e1bcfc085f2b2787ff98005d0075e55451f1e0832885e3d9642a"),
            TranslationModelFile(Role.MODEL, "model.fren.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.fren.intgemm.alphas.bin.gz", 23175075, 31561787, "06b1eeedd3944260d00a393d12ec7192490c5b7c930b97212faf4d5f5c90a2ee"),
            TranslationModelFile(Role.VOCAB, "vocab.fren.spm", "$TRANSLATION_MODELS_RELEASE/vocab.fren.spm.gz", 409706, 814404, "8d15b219ffd32327b4cabf0d94a05a4fecb8923a4f386badbcbe5e86ede453a7"),
        )),
        TranslationDirection("en", "fr", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enfr.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enfr.s2t.bin.gz", 2297334, 4372936, "055987f0b585b61c4914fb4469e2392fda0b25d3f7784275974f920e7b631997"),
            TranslationModelFile(Role.MODEL, "model.enfr.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enfr.intgemm.alphas.bin.gz", 23045432, 31561787, "22cdaf3dc9a1da6e5818b5576737182467f3cd97e6fd6f94e4273eb7b56d1e3f"),
            TranslationModelFile(Role.VOCAB, "vocab.enfr.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enfr.spm.gz", 409706, 814404, "5dcadaad8191fb4eb7677bce07098a20221dec95976a4db796f3a17cc82b4541"),
        )),
    ),
    TranslationLanguage(
        "gl",
        TranslationDirection("gl", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.glen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.glen.s2t.bin.gz", 2191952, 4367596, "ad9d0fd9d086347d4203c30a48b8d70454e5f47b208aeba71885b43b582f1546"),
            TranslationModelFile(Role.MODEL, "model.glen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.glen.intgemm.alphas.bin.gz", 23054964, 31561787, "bb1816755766dbb88c6eb8668cdd4aab49f2734acc58645e898696e42bc93d87"),
            TranslationModelFile(Role.VOCAB, "vocab.glen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.glen.spm.gz", 410400, 827023, "62378ca0109bb10f85c0b2c4999dc947452bd500539bfc63f9d61a43b0a7dc8f"),
        )),
        TranslationDirection("en", "gl", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.engl.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.engl.s2t.bin.gz", 1598079, 3007680, "3df735baa7c32d22d2e8d42f7279fbcc059e384f5c60be6f641dd621a5ea756d"),
            TranslationModelFile(Role.MODEL, "model.engl.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.engl.intgemm.alphas.bin.gz", 23427851, 31561787, "a1c5bb32756e0165ac3cb9cd5d68eabb08db5d649d532e38be0728729bbb33ef"),
            TranslationModelFile(Role.VOCAB, "vocab.engl.spm", "$TRANSLATION_MODELS_RELEASE/vocab.engl.spm.gz", 410563, 827026, "160e04cc1f2b165d7f17b27027c74d144660589b155f17832ad754657cd8587e"),
        )),
    ),
    TranslationLanguage(
        "gu",
        TranslationDirection("gu", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.guen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.guen.s2t.bin.gz", 2028621, 4197836, "30b6417f113a993a73fb9f6b58db94df23e2a2192fe0f70b3a422019ccf33d31"),
            TranslationModelFile(Role.MODEL, "model.guen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.guen.intgemm.alphas.bin.gz", 12917932, 17141051, "f78d8f7120b7e3092f83639f4b2600459ea016dabaed037f20e651d015ca070a"),
            TranslationModelFile(Role.VOCAB, "vocab.guen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.guen.spm.gz", 435011, 965143, "3113b3e5e6d507555858fda228517d407ebabc39d5d7e6e1522f9aa8f083a598"),
        )),
        TranslationDirection("en", "gu", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.engu.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.engu.s2t.bin.gz", 1529098, 3179500, "2ab0f92654a4314fc64ad52cfec32aaa1d187e969d209990fcac41c96a5073ae"),
            TranslationModelFile(Role.MODEL, "model.engu.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.engu.intgemm.alphas.bin.gz", 12657911, 17141051, "66003a2deb5b2bdf65748c344dbbb94d73b8f225aea3a66caab17b41c5e0ad2e"),
            TranslationModelFile(Role.VOCAB, "vocab.engu.spm", "$TRANSLATION_MODELS_RELEASE/vocab.engu.spm.gz", 434881, 965095, "9f79169080b255c5683d9ad6cc263724b09b215cc1010cd7b9a2f5de2dcd5748"),
        )),
    ),
    TranslationLanguage(
        "he",
        TranslationDirection("he", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.heen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.heen.s2t.bin.gz", 2232949, 4636028, "49691f4355a870ad49137100d1559b2e3505b7c4419d47e5261b6e772264c2fc"),
            TranslationModelFile(Role.MODEL, "model.heen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.heen.intgemm.alphas.bin.gz", 12999905, 17141051, "42b8846343a6bda677c20846622bdb9087a84ab37b0b50d90f3e6135b622505f"),
            TranslationModelFile(Role.VOCAB, "vocab.heen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.heen.spm.gz", 411769, 845177, "780458822f46ab6471bd531223fa87ebd408140f16f3d6d6e3136c0b410bd316"),
        )),
        TranslationDirection("en", "he", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enhe.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enhe.s2t.bin.gz", 1567190, 3066048, "8dda768bc3a852547dd141e2945cdd9667eb2ffa3837bdb4a917f3f95481897c"),
            TranslationModelFile(Role.MODEL, "model.enhe.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enhe.intgemm.alphas.bin.gz", 12979964, 17141051, "61a2281fbef3dc440c9e9a8a3c064e34addf4a63fe584b1e523b7ee809b1870e"),
            TranslationModelFile(Role.VOCAB, "vocab.enhe.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enhe.spm.gz", 411686, 845017, "4eee1f6ed468177c2397976cfaddaa58a61966944a732579957cc27b480b7ab6"),
        )),
    ),
    TranslationLanguage(
        "hi",
        TranslationDirection("hi", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.hien.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.hien.s2t.bin.gz", 2319675, 4605984, "9647fd7a38db4bafa549f73bf34cabd5a415cd34f3acd7212fced93f163dbd49"),
            TranslationModelFile(Role.MODEL, "model.hien.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.hien.intgemm.alphas.bin.gz", 12752013, 17141051, "d30d257188bec64fceeb37483a6be8c54f1246583ad4e4f99dda174b630afeb3"),
            TranslationModelFile(Role.VOCAB, "vocab.hien.spm", "$TRANSLATION_MODELS_RELEASE/vocab.hien.spm.gz", 430096, 925436, "7554161ff543abf09200b4feec83328259b0acb0e58003d834ad43bac47f6124"),
        )),
        TranslationDirection("en", "hi", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enhi.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enhi.s2t.bin.gz", 1690062, 3504820, "ce5f1dd9d4fb343cb6e0da91e4603e50b673b91ea22b50b959a0dc199d4e9dd9"),
            TranslationModelFile(Role.MODEL, "model.enhi.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enhi.intgemm.alphas.bin.gz", 12736263, 17141051, "751032330fe04b9dd4e1245c4dcf8f58dd6836daa7ed3f3b93be52eb1fca9ba4"),
            TranslationModelFile(Role.VOCAB, "vocab.enhi.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enhi.spm.gz", 430026, 925360, "bb3bf8252b14fa57100beb371824cf51a7281e833a3becec135721fe679ce076"),
        )),
    ),
    TranslationLanguage(
        "hu",
        TranslationDirection("hu", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.huen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.huen.s2t.bin.gz", 2433968, 4847184, "1c3183ac06603c24bc591eb68f96bc8d7398a3e962ae406799b7fee064e2d35d"),
            TranslationModelFile(Role.MODEL, "model.huen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.huen.intgemm.alphas.bin.gz", 22582446, 31561787, "d864f7fbac38f7c0e3d9472d5a66776130440f7505126dcbe2238b9ffe897e8f"),
            TranslationModelFile(Role.VOCAB, "vocab.huen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.huen.spm.gz", 421716, 832895, "60fee5e35a452369e2920f6e2377d0da59df673945137af90040bfd46b3d5f6a"),
        )),
        TranslationDirection("en", "hu", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enhu.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enhu.s2t.bin.gz", 1794658, 3419024, "b504786f6e25eb788272d07cdaa331f9ff7e15728d272c2420319b2b172cf0ef"),
            TranslationModelFile(Role.MODEL, "model.enhu.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enhu.intgemm.alphas.bin.gz", 22889950, 31561787, "3c0d834c5b4542b5af34c2fe97cab15bd13f41192b4b5f1269c43d8376f8d5d8"),
            TranslationModelFile(Role.VOCAB, "vocab.enhu.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enhu.spm.gz", 421527, 832855, "a3d762e07561ede58968703ed9dbcb0b281fbb1a58c99160dd2cb1fffa2feb04"),
        )),
    ),
    TranslationLanguage(
        "id",
        TranslationDirection("id", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.iden.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.iden.s2t.bin.gz", 1818222, 4050348, "029091e65df311e17c7e5a199505372dc3892937046b918ac18695aede08e344"),
            TranslationModelFile(Role.MODEL, "model.iden.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.iden.intgemm.alphas.bin.gz", 13010657, 17141051, "625c237e7d1cdc12b0d9e2e666c0d3b674e13d50461268467aaa0b78c2cc5d93"),
            TranslationModelFile(Role.VOCAB, "vocab.iden.spm", "$TRANSLATION_MODELS_RELEASE/vocab.iden.spm.gz", 379859, 772941, "74daf618f0c78d508fda867f30983e9e5679a4e21c4cd42f5dcd5e501448f48e"),
        )),
        TranslationDirection("en", "id", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enid.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enid.s2t.bin.gz", 1734565, 3515428, "41853979c81022487542eceed4994078bd144c63fff84a421616f3cc8f3162c1"),
            TranslationModelFile(Role.MODEL, "model.enid.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enid.intgemm.alphas.bin.gz", 12503257, 17141051, "08bf854041ee20e955c013f17d86ae562b29388304151071e176b579e78fb0be"),
            TranslationModelFile(Role.VOCAB, "vocab.enid.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enid.spm.gz", 379806, 773211, "49af04de6f0e3c21afcb274e7a6931c8f9efae38932e2671b692bf1b6f6d279b"),
        )),
    ),
    TranslationLanguage(
        "is",
        TranslationDirection("is", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.isen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.isen.s2t.bin.gz", 2012853, 3951884, "a6a84f722b707da7684a47088ee569ebf8703ac210fa7655a871fa8fc4d0be95"),
            TranslationModelFile(Role.MODEL, "model.isen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.isen.intgemm.alphas.bin.gz", 23229378, 31561787, "b718b397b3c5cd1227bdfff61f5103a63991f73ecd47d462cccafbdbda4647b2"),
            TranslationModelFile(Role.VOCAB, "vocab.isen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.isen.spm.gz", 412304, 808315, "410332d7d2821eda3697d7b69748fe11510eedcd8a62a4aa5b014fc5be16b728"),
        )),
        TranslationDirection("en", "is", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enis.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enis.s2t.bin.gz", 1977789, 3837564, "ac58e32149fde7fc848312ff4eb2b41679d08d2244ee329085d147bd776457e9"),
            TranslationModelFile(Role.MODEL, "model.enis.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enis.intgemm.alphas.bin.gz", 22588003, 31561787, "2197e9070d9da37ad15cd9b71650006bc1703ef84b09e136d25dbda025a793df"),
            TranslationModelFile(Role.VOCAB, "vocab.enis.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enis.spm.gz", 413543, 809991, "38d5822b0b6de5198d28c0c60fd87b3957d2b02b1bc9882778e6cc04dc8a79db"),
        )),
    ),
    TranslationLanguage(
        "it",
        TranslationDirection("it", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.iten.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.iten.s2t.bin.gz", 2532929, 4713616, "504877085b31edfa3d31a1918a9a42c20fcbf85ff018caf46c54641db5538e62"),
            TranslationModelFile(Role.MODEL, "model.iten.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.iten.intgemm.alphas.bin.gz", 23301774, 31561787, "0bc7221c2730723ac4477e8aa1d1d5bd0b9c3450cb8d006a6f86fe5da9129c27"),
            TranslationModelFile(Role.VOCAB, "vocab.iten.spm", "$TRANSLATION_MODELS_RELEASE/vocab.iten.spm.gz", 407598, 812724, "df05fae498f519a828eb388cd08ec1b7205a8bcaf2405a5feb9f5e30c49a0977"),
        )),
        TranslationDirection("en", "it", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enit.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enit.s2t.bin.gz", 2209348, 4133192, "cd7ef06c0b872c15286a9796f105eb62693f14665490546ac70ce1c6c8f16d47"),
            TranslationModelFile(Role.MODEL, "model.enit.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enit.intgemm.alphas.bin.gz", 23892889, 31561787, "cfff470e9f29e27132723589a8bc985648f92773410e5f6fc43293d9e19f97f1"),
            TranslationModelFile(Role.VOCAB, "vocab.enit.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enit.spm.gz", 407598, 812724, "8f99a6f493bf7e1a03fbba19928d7dc7bf9a1b7938238467f3e80a58c0d50485"),
        )),
    ),
    TranslationLanguage(
        "ja",
        TranslationDirection("ja", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.jaen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.jaen.s2t.bin.gz", 4819610, 9348172, "438152f5ccd982edb43e88ef51305e3ae7c7b66ee5c20a8fa425e9f1822f9b9b"),
            TranslationModelFile(Role.MODEL, "model.jaen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.jaen.intgemm.alphas.bin.gz", 32577435, 43977787, "ae56ffbb5556d8e4240b2f208a7c7a2449a4b627ac9d673981ed29eaadaab79d"),
            TranslationModelFile(Role.VOCAB, "vocab.jaen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.jaen.spm.gz", 746616, 1443222, "12d693f5055525d5cc1e133c8c1b8ed787c77b9bb797400d9a14382ac69c1236"),
        )),
        TranslationDirection("en", "ja", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enja.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enja.s2t.bin.gz", 2341409, 4128360, "7966382f7a9ba15993c67721526921d8901caa0f8add56eff04e4bb327d57c11"),
            TranslationModelFile(Role.MODEL, "model.enja.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enja.intgemm.alphas.bin.gz", 33052218, 43849787, "99fc8fc120189930beadacb2eef4b049d0794ac6132d1266340e457c95730368"),
            TranslationModelFile(Role.SOURCE_VOCAB, "srcvocab.enja.spm", "$TRANSLATION_MODELS_RELEASE/srcvocab.enja.spm.gz", 404352, 796275, "12d8ffc83fc0bb61494d95701f6a298bbad5c999a043d4a48a1c1bd61e092167"),
            TranslationModelFile(Role.TARGET_VOCAB, "trgvocab.enja.spm", "$TRANSLATION_MODELS_RELEASE/trgvocab.enja.spm.gz", 431278, 827144, "be7fec234b5fc94616276ee6cca69f3a8cbfa6762fdf278dfc6b11eaf669cc48"),
        )),
    ),
    TranslationLanguage(
        "kn",
        TranslationDirection("kn", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.knen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.knen.s2t.bin.gz", 2128860, 4655776, "307468def521e5d4ede3b8699e10b5328958a57642293df22f5bc357688b474b"),
            TranslationModelFile(Role.MODEL, "model.knen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.knen.intgemm.alphas.bin.gz", 13077357, 17141051, "1c5aaf6fd69400dd13e519f321aad0577bd0bcdbee0e87097582dc037dc51f05"),
            TranslationModelFile(Role.VOCAB, "vocab.knen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.knen.spm.gz", 450324, 1065636, "739e6f45a056331f869328a2999d20952a33c5204516a5b3dc36d34020603e36"),
        )),
        TranslationDirection("en", "kn", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enkn.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enkn.s2t.bin.gz", 1416160, 2808304, "3227fa0bba2fbec768b2648fec014bea5cb5384d85c0199afb36abe5281db658"),
            TranslationModelFile(Role.MODEL, "model.enkn.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enkn.intgemm.alphas.bin.gz", 13009213, 17141051, "e7f684fea84a6a69522e77388fd09f015b513511ed36192f0493d0faf52380ad"),
            TranslationModelFile(Role.VOCAB, "vocab.enkn.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enkn.spm.gz", 450046, 1065180, "2a501f3862d4e27269c457f82084a714a03f44b7e05ce92daef5dff0389f8860"),
        )),
    ),
    TranslationLanguage(
        "ko",
        TranslationDirection("ko", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.koen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.koen.s2t.bin.gz", 4381854, 8617516, "92d595d9e7cab334cf4560c4f66d0439bc4b9aeb644852f4eb280ccaf9aed587"),
            TranslationModelFile(Role.MODEL, "model.koen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.koen.intgemm.alphas.bin.gz", 32152814, 43977787, "1fa9af76c6a954fce14243d698c02edea38b74b1f3d149ca6a4d7f8f88ba1b92"),
            TranslationModelFile(Role.VOCAB, "vocab.koen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.koen.spm.gz", 706864, 1410063, "3b17fba7f58bde82f4ebd7ea0f51fa96fc22c8c5c20a4e905e0498f6da0ca46c"),
        )),
        TranslationDirection("en", "ko", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enko.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enko.s2t.bin.gz", 3471311, 6449612, "062ceb1b1173f81c5ece40fb45affb5b7cbd8eaaf295e5744647d0e94b04beef"),
            TranslationModelFile(Role.MODEL, "model.enko.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enko.intgemm.alphas.bin.gz", 33738001, 43849787, "91ebb959edc11b6ff63d28b5e237106047673e5be2dfec99169352fd98f0f1be"),
            TranslationModelFile(Role.SOURCE_VOCAB, "srcvocab.enko.spm", "$TRANSLATION_MODELS_RELEASE/srcvocab.enko.spm.gz", 402480, 791280, "2227e5841e4376a3de47010a22f77762d9259c7459959744f2505721b93134a3"),
            TranslationModelFile(Role.TARGET_VOCAB, "trgvocab.enko.spm", "$TRANSLATION_MODELS_RELEASE/trgvocab.enko.spm.gz", 412614, 815353, "676f821c4e0bab2f6b5af0e38fffdb7c053ad74ffa5a3e822e55fd2370af4008"),
        )),
    ),
    TranslationLanguage(
        "lt",
        TranslationDirection("lt", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.lten.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.lten.s2t.bin.gz", 2308876, 4724124, "1851b00216bd8f6bac64223757fd547bb79e0b99b3a032078dab12f5f27a195e"),
            TranslationModelFile(Role.MODEL, "model.lten.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.lten.intgemm.alphas.bin.gz", 12571257, 17141051, "88fa4bb09798d0f52d67f4f45a8540fdd4727bc1481cedc153dec4dc70ab892b"),
            TranslationModelFile(Role.VOCAB, "vocab.lten.spm", "$TRANSLATION_MODELS_RELEASE/vocab.lten.spm.gz", 403960, 807623, "3be489b994ec61caa9ab9a0bd5cd6d5253daacf45f0cf7dcbc2bb56a8c25391c"),
        )),
        TranslationDirection("en", "lt", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enlt.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enlt.s2t.bin.gz", 1769752, 3421640, "50fac179bb99a9cabbe3dea1f7d23df50b8342cad4fe8fe4ba93ad31e36a867b"),
            TranslationModelFile(Role.MODEL, "model.enlt.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enlt.intgemm.alphas.bin.gz", 22865642, 31561787, "5ad6f4e62d3ef8cc63310bcce79c69ea59c2c25bb7b966bcc269ca32dcacc004"),
            TranslationModelFile(Role.VOCAB, "vocab.enlt.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enlt.spm.gz", 403356, 806827, "a337b0ec21968a4dbdb147e755f9b34f59ae438192f7148da607dbae9c839b87"),
        )),
    ),
    TranslationLanguage(
        "lv",
        TranslationDirection("lv", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.lven.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.lven.s2t.bin.gz", 2131786, 4214476, "720f6d513f64275daf17b7a9bf78835a442819fbf2d24ba199a3a1088349cfc0"),
            TranslationModelFile(Role.MODEL, "model.lven.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.lven.intgemm.alphas.bin.gz", 12689153, 17141051, "81d5f3b41f22c1759ce1398769e7732d8eb59b6056d6c46ad915e6ace05c6e01"),
            TranslationModelFile(Role.VOCAB, "vocab.lven.spm", "$TRANSLATION_MODELS_RELEASE/vocab.lven.spm.gz", 407237, 815278, "8d4e565e5f39f6e0d5033c4b2fdfc5c1e85a5857f28859765f98ced0366a4a8d"),
        )),
        TranslationDirection("en", "lv", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enlv.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enlv.s2t.bin.gz", 1725879, 3359096, "f5cdd08a781f95aaa8473c0286d4878a7935aedd591b4ce00abc2a30a5a0c5d9"),
            TranslationModelFile(Role.MODEL, "model.enlv.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enlv.intgemm.alphas.bin.gz", 23727668, 31561787, "559b5f51424888b10b1872e7348906e946ac702d62b1ef9872ecb49ea865537d"),
            TranslationModelFile(Role.VOCAB, "vocab.enlv.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enlv.spm.gz", 407540, 816287, "9a76e5785b64445762b1771ba9c15468e20794530e332880a25999362c7c7774"),
        )),
    ),
    TranslationLanguage(
        "ml",
        TranslationDirection("ml", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.mlen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.mlen.s2t.bin.gz", 2296381, 5017972, "27e7301494d48bed602e409d891a6501557d03c534610eb2c5eba0a9507a829b"),
            TranslationModelFile(Role.MODEL, "model.mlen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.mlen.intgemm.alphas.bin.gz", 12792306, 17141051, "bb63f0267cb901f23c4fc664f1d50a2b4890900980486bedc9080cc5d19914a7"),
            TranslationModelFile(Role.VOCAB, "vocab.mlen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.mlen.spm.gz", 454911, 1109047, "f5f0084c423c71fdca2a4c54a862b65de35f748f1b189c0a950fc57bf03a37e7"),
        )),
        TranslationDirection("en", "ml", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enml.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enml.s2t.bin.gz", 1275347, 2532960, "f8b294d0a490b8dfd60d300cc6688eef6fcb5f519f9b17ac05c137bb20bfc804"),
            TranslationModelFile(Role.MODEL, "model.enml.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enml.intgemm.alphas.bin.gz", 12570038, 17141051, "276ea5a40a974ac039ff83e0594986a8110820602eedff616838e8914e2e6d91"),
            TranslationModelFile(Role.VOCAB, "vocab.enml.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enml.spm.gz", 454768, 1109000, "388cfec515765b48792a0be3fb383f9dc6aefbd646c1e09ec3440fc8ce18a6df"),
        )),
    ),
    TranslationLanguage(
        "mr",
        TranslationDirection("mr", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.mren.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.mren.s2t.bin.gz", 2327949, 4534544, "7ef1c10621b5dad2475582477d4b19a325d9b1742d07467c11732962bee0d73b"),
            TranslationModelFile(Role.MODEL, "model.mren.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.mren.intgemm.alphas.bin.gz", 22289099, 31561787, "2567f631a3dea1e36c6e8cfd561220ddc35752589de7869b01a7b58deb26f545"),
            TranslationModelFile(Role.VOCAB, "vocab.mren.spm", "$TRANSLATION_MODELS_RELEASE/vocab.mren.spm.gz", 443184, 1009482, "4cc85cb2bdd625afc12009d69a060e370b9045abe7e411e6afb36bd703b924ca"),
        )),
        TranslationDirection("en", "mr", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enmr.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enmr.s2t.bin.gz", 1401383, 2731352, "d82ee8a5263ea6ea6f381fe3b7dbb5c1b9824b4b913624d13d06f7ecba3b17f9"),
            TranslationModelFile(Role.MODEL, "model.enmr.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enmr.intgemm.alphas.bin.gz", 22896929, 31561787, "abe49fc43de91f56acaa9a54ca12af46af54831536ceff05d44f1884646a0c14"),
            TranslationModelFile(Role.VOCAB, "vocab.enmr.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enmr.spm.gz", 443275, 1009700, "7b0177f027fb647137a9907b51584593a77679fdd6b3a8b296016e2f4b4b1615"),
        )),
    ),
    TranslationLanguage(
        "ms",
        TranslationDirection("ms", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.msen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.msen.s2t.bin.gz", 2141259, 4371896, "456ad116209370d6ba4b5f90c4143ee008d02610dea582922b1b2d6cff0b0200"),
            TranslationModelFile(Role.MODEL, "model.msen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.msen.intgemm.alphas.bin.gz", 12538542, 17141051, "de212e0d42428858ee96027329ab1d55a6e77754ecaaa17ab58ad03e71c16fb1"),
            TranslationModelFile(Role.VOCAB, "vocab.msen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.msen.spm.gz", 403877, 802191, "1755f6619ae37dc8d694ebbec7b095b014ce6dc27ed8aac37bd7c749192e6997"),
        )),
        TranslationDirection("en", "ms", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enms.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enms.s2t.bin.gz", 2044118, 3936428, "af50b88c0072cc3762774f2d5021911cbf40e577cf2903e80824397e5abdffb1"),
            TranslationModelFile(Role.MODEL, "model.enms.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enms.intgemm.alphas.bin.gz", 13039668, 17141051, "d067740465b320693c79d9ebe32b9de911a3340d0a0b2ff408a3e9126980af49"),
            TranslationModelFile(Role.VOCAB, "vocab.enms.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enms.spm.gz", 404033, 802440, "26c4054e6712e3ad44a4a28ebb4e91dcd0f9b41848997bbfaf90ba5aee3fc99c"),
        )),
    ),
    TranslationLanguage(
        "nb",
        TranslationDirection("nb", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.nben.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.nben.s2t.bin.gz", 2308582, 4517876, "0b80d2283d85c453f02e5ec63488359247f3e47669ff2a5d01c9bebf54df20eb"),
            TranslationModelFile(Role.MODEL, "model.nben.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.nben.intgemm.alphas.bin.gz", 13193689, 17141051, "61d94f5f3a514f6b54fa488f0de97ca8edea40509eab8bbfd3f25ba565353874"),
            TranslationModelFile(Role.VOCAB, "vocab.nben.spm", "$TRANSLATION_MODELS_RELEASE/vocab.nben.spm.gz", 409135, 802367, "0801a124577a9f303084ac70c25513bbecf9e478d81493b97c0a8186a769e196"),
        )),
        TranslationDirection("en", "nb", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.ennb.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.ennb.s2t.bin.gz", 2193397, 4234572, "167cf6486244d0058495f7705ceda5635a2c58a605c4ad39357622080cf4e93d"),
            TranslationModelFile(Role.MODEL, "model.ennb.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.ennb.intgemm.alphas.bin.gz", 12713727, 17141051, "c543860054818a8a5f6bf0fa782c9c538658b35bcb01bf0f56f7f880e25f6b7e"),
            TranslationModelFile(Role.VOCAB, "vocab.ennb.spm", "$TRANSLATION_MODELS_RELEASE/vocab.ennb.spm.gz", 409037, 802190, "76e2cc7654d8282a8dc5b139a78d047aa2e71563cf671bd15f4dfc9bfdf75dad"),
        )),
    ),
    TranslationLanguage(
        "nl",
        TranslationDirection("nl", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.nlen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.nlen.s2t.bin.gz", 2616098, 4862412, "ddc7811550e820a081353556f5b5bfdc907251a20850e945bfc887bcd28f8c56"),
            TranslationModelFile(Role.MODEL, "model.nlen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.nlen.intgemm.alphas.bin.gz", 22647743, 31561787, "ed02d0f965fa78335a7ef326337267c04c5c444a7261ab4cdeb82fcfbb67d617"),
            TranslationModelFile(Role.VOCAB, "vocab.nlen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.nlen.spm.gz", 410222, 807708, "12c2bb8bf4d7b39cba7dc1b3eb16232ea29f1325e963eb9a29d7cc886c306599"),
        )),
        TranslationDirection("en", "nl", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.ennl.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.ennl.s2t.bin.gz", 2155034, 4030624, "b95c612e69270142c352589b4082b936810ec02ab7842c2a573bab6441709d06"),
            TranslationModelFile(Role.MODEL, "model.ennl.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.ennl.intgemm.alphas.bin.gz", 23386633, 31561787, "a1ab24477ca1289e123e9a2817434f99b47b9b5e461ec65ad273f3dd394814a2"),
            TranslationModelFile(Role.VOCAB, "vocab.ennl.spm", "$TRANSLATION_MODELS_RELEASE/vocab.ennl.spm.gz", 410222, 807708, "0b12be4ccd0ee5182ad7e8ecd3254eece806ae183bece90fa625ceae7c851f80"),
        )),
    ),
    TranslationLanguage(
        "pl",
        TranslationDirection("pl", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.plen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.plen.s2t.bin.gz", 2489764, 4964208, "7ad8ce0f56b7537a82e7e522a48ea440395a909c547621934cf70daa1c543c36"),
            TranslationModelFile(Role.MODEL, "model.plen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.plen.intgemm.alphas.bin.gz", 22630393, 31561787, "7f37aa5e065581c02fbd5fd4f3862a714944e223055edafe23095a68f3a49a76"),
            TranslationModelFile(Role.VOCAB, "vocab.plen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.plen.spm.gz", 413194, 821612, "90f3d5a707eb8b221ab4139de6146e4741ab3196fbadf4562b03d727a0f8b822"),
        )),
        TranslationDirection("en", "pl", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enpl.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enpl.s2t.bin.gz", 1874327, 3540052, "6e7cbf38d9298877d9631a33a7bd3608326ba169be9a0fe9c7b2ee0c6c7e6d59"),
            TranslationModelFile(Role.MODEL, "model.enpl.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enpl.intgemm.alphas.bin.gz", 22577447, 31561787, "80b549e5f4d1d1db3f66f850c71683c9449a259e6eac2abe3b8f04f0781088ed"),
            TranslationModelFile(Role.VOCAB, "vocab.enpl.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enpl.spm.gz", 413194, 821612, "13b8f1dc8bf7a29d052008d78aa4429b1311f8fd0fcb63c5490fe1714b00606c"),
        )),
    ),
    TranslationLanguage(
        "pt",
        TranslationDirection("pt", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.pten.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.pten.s2t.bin.gz", 2487847, 4634492, "b31185389533a97177cbf68ea756b78bfbaa24d31a865d72c6ed203fa414b2f6"),
            TranslationModelFile(Role.MODEL, "model.pten.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.pten.intgemm.alphas.bin.gz", 22700409, 31561787, "f2d2bb46d452cef561d35504bd198fa6c6ffc47187ee987406a2ac05d9c3935f"),
            TranslationModelFile(Role.VOCAB, "vocab.pten.spm", "$TRANSLATION_MODELS_RELEASE/vocab.pten.spm.gz", 408686, 816726, "28c9eb4fb13f8eb661f6bb098560a1bf368d25ff890275028ea9d4f3f97b0416"),
        )),
        TranslationDirection("en", "pt", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enpt.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enpt.s2t.bin.gz", 2117608, 3970340, "265cff4ca31d3fc95628181de98cf668868b44903d69680284dc456aa4191545"),
            TranslationModelFile(Role.MODEL, "model.enpt.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enpt.intgemm.alphas.bin.gz", 23340019, 31561787, "afb5ae08a2e40b622cd191584cca1df00721fea43de85cec74191fc180370f08"),
            TranslationModelFile(Role.VOCAB, "vocab.enpt.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enpt.spm.gz", 408686, 816726, "c2fbaf26f10563c77fa95cca465ad3666f61dd08bfaef5bb170abd582901f389"),
        )),
    ),
    TranslationLanguage(
        "ro",
        TranslationDirection("ro", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.roen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.roen.s2t.bin.gz", 2159556, 4691708, "3b3fdee9bb65fe9053c4a1a5ae2bdfe6a4c251a329bd49b45ea9af8864baf7ea"),
            TranslationModelFile(Role.MODEL, "model.roen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.roen.intgemm.alphas.bin.gz", 12722200, 17141051, "217b5a3bf0aed1a2c9c47259159a4ec09fa673bf10049d23fe15902147e66785"),
            TranslationModelFile(Role.VOCAB, "vocab.roen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.roen.spm.gz", 396717, 800832, "0f7ce73533f0c8549d8498c67e2db7502654a462ed81de687ba666dc4cf64706"),
        )),
        TranslationDirection("en", "ro", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enro.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enro.s2t.bin.gz", 1846074, 3739880, "a64099f219a6e4eee89085283ace66e8f0171d43b168ba155dffc2fa4dcdc9b1"),
            TranslationModelFile(Role.MODEL, "model.enro.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enro.intgemm.alphas.bin.gz", 12207487, 17141051, "3596ee3bc1461c96f28edf200f4235fdfd4e0cb8434fa86ad04762d4a10d7a66"),
            TranslationModelFile(Role.VOCAB, "vocab.enro.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enro.spm.gz", 397137, 801522, "61a75f040f035844ec5d54edf5f80831cd8ad58bfa539a7e707a7f6a5bd25c63"),
        )),
    ),
    TranslationLanguage(
        "ru",
        TranslationDirection("ru", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.ruen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.ruen.s2t.bin.gz", 2139703, 4397908, "012674431e3a248e5f647e88e254331eca37f661960ea82ceb93dab78850ccd8"),
            TranslationModelFile(Role.MODEL, "model.ruen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.ruen.intgemm.alphas.bin.gz", 22805722, 31561787, "1dc70ffc7dce84d46ad13b8c1908c46f0dfbf4e2ed1daaffb8b8b04315e00aa3"),
            TranslationModelFile(Role.VOCAB, "vocab.ruen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.ruen.spm.gz", 441622, 952371, "20f7d8032b12a7c1bba99784fca60ccf1d49e782f3cad8791e8cf0c2063b334c"),
        )),
        TranslationDirection("en", "ru", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enru.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enru.s2t.bin.gz", 1378563, 2774540, "9c111984d8207f8dc6b9dd5c17ab4d18042f7c0e34105a09a35909538facc958"),
            TranslationModelFile(Role.MODEL, "model.enru.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enru.intgemm.alphas.bin.gz", 21988864, 31561787, "e766bc83434f4a9ff4110abe5450043a62cd402c6a7a8bca5e3e4d83b408dcb4"),
            TranslationModelFile(Role.VOCAB, "vocab.enru.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enru.spm.gz", 419005, 904455, "9aa498dce5d27c02ac998c646c51a7475a421500ecdbbd1dff9ff3e77e64b21c"),
        )),
    ),
    TranslationLanguage(
        "sk",
        TranslationDirection("sk", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.sken.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.sken.s2t.bin.gz", 2348184, 4913324, "08fceba612fbf6f833ab188e1f7125c091656cdca2c886c84fca29e3960ddb16"),
            TranslationModelFile(Role.MODEL, "model.sken.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.sken.intgemm.alphas.bin.gz", 12821519, 17141051, "5825c97bfc80435071da744ef05444119cac81f6bf80eeecd80098c741a04a4b"),
            TranslationModelFile(Role.VOCAB, "vocab.sken.spm", "$TRANSLATION_MODELS_RELEASE/vocab.sken.spm.gz", 405122, 808082, "3954450491e4470532267c6af9ae05fc9dfc1a739c7fbea0dc0ea83cc3e1eba4"),
        )),
        TranslationDirection("en", "sk", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.ensk.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.ensk.s2t.bin.gz", 1708788, 3356348, "a772fa9a45d574bfedeeb6d92c7e7f8b0a8e765d5f7517cc62f8a847517a29b9"),
            TranslationModelFile(Role.MODEL, "model.ensk.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.ensk.intgemm.alphas.bin.gz", 22902983, 31561787, "71cec9a790bb24e673d47f41f2778491f5a84d00663fc739f94f50bcf0f49940"),
            TranslationModelFile(Role.VOCAB, "vocab.ensk.spm", "$TRANSLATION_MODELS_RELEASE/vocab.ensk.spm.gz", 405652, 808888, "8fe4f76b56a8fa4aa48c60433306f536d19805116e104fc8230b3681ee99a8ed"),
        )),
    ),
    TranslationLanguage(
        "sl",
        TranslationDirection("sl", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.slen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.slen.s2t.bin.gz", 2138548, 4320484, "09724499bd2a9abf5e2869642438adfc4a6e300069d0e0ec8ef18320441b58e6"),
            TranslationModelFile(Role.MODEL, "model.slen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.slen.intgemm.alphas.bin.gz", 23730414, 31561787, "ea4929781045086ea37e689fda03dfb75e77e5abaa10a43ae0f8ea252c248040"),
            TranslationModelFile(Role.VOCAB, "vocab.slen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.slen.spm.gz", 398535, 803078, "2887bddbbd49efc3a26b1e787cb3fe2d343db05ec9f209413bd735e505144105"),
        )),
        TranslationDirection("en", "sl", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.ensl.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.ensl.s2t.bin.gz", 1741316, 3428300, "c7b803feb615b1442e1caf4c3a4d34fd7660dc31ac1088146ad410e338a5391a"),
            TranslationModelFile(Role.MODEL, "model.ensl.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.ensl.intgemm.alphas.bin.gz", 22669559, 31561787, "851c720e75803a92dae757086345cf5a3cd25740cc9990d08c42b234533d7601"),
            TranslationModelFile(Role.VOCAB, "vocab.ensl.spm", "$TRANSLATION_MODELS_RELEASE/vocab.ensl.spm.gz", 398763, 803212, "07d9137c7e54457325d6b5220382b5f184d34903fa99cabc10f7b98869220124"),
        )),
    ),
    TranslationLanguage(
        "sv",
        TranslationDirection("sv", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.sven.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.sven.s2t.bin.gz", 2165215, 4645680, "aedabe4633446cf85b3e2ecc4139b88efed4c5a39b41d2f0d0bb99494c6b950c"),
            TranslationModelFile(Role.MODEL, "model.sven.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.sven.intgemm.alphas.bin.gz", 12847259, 17141051, "5a5351596bc22c517908628924ac63bec5f81e7225c62bf6e42bb7c66cb41987"),
            TranslationModelFile(Role.VOCAB, "vocab.sven.spm", "$TRANSLATION_MODELS_RELEASE/vocab.sven.spm.gz", 397625, 793049, "75c1784afa8d4b94d2f6ce064fb2facc2044c3cedfc0fbe25acd85f32b06589e"),
        )),
        TranslationDirection("en", "sv", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.ensv.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.ensv.s2t.bin.gz", 1921270, 3948180, "0480c83e15f1d2dcee68873eee5fb66c2912884ab2757ff201e6b6ab9be38ed7"),
            TranslationModelFile(Role.MODEL, "model.ensv.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.ensv.intgemm.alphas.bin.gz", 12775086, 17141051, "f2fee438e0770428c06a4fa1e938175bf7c37f3a288313c317853b646437eb81"),
            TranslationModelFile(Role.VOCAB, "vocab.ensv.spm", "$TRANSLATION_MODELS_RELEASE/vocab.ensv.spm.gz", 398384, 793868, "534e7f952f6bb97903301332836bab5d76cbc965592a9f1af77ace05e84e2edf"),
        )),
    ),
    TranslationLanguage(
        "ta",
        TranslationDirection("ta", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.taen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.taen.s2t.bin.gz", 2410364, 4940884, "8842f8c6cdb15abc7523c706a3d99dd6d4f4eefb03625752fb5dda3a3195296f"),
            TranslationModelFile(Role.MODEL, "model.taen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.taen.intgemm.alphas.bin.gz", 23526938, 31561787, "f3cafdc392a0d2f8354d8eb6913aa8654b1e1f91a50554922fe82f05aa33d178"),
            TranslationModelFile(Role.VOCAB, "vocab.taen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.taen.spm.gz", 451486, 1104678, "0e34d4d07742c809b26f756aa7d3eaa05b00d9d2d472d1646002b8f574e87e00"),
        )),
        TranslationDirection("en", "ta", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enta.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enta.s2t.bin.gz", 1434399, 2746824, "49cef4534549e65f20eb34685f619d235d1e081856eb98f7e4e7f72ad04dae7c"),
            TranslationModelFile(Role.MODEL, "model.enta.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enta.intgemm.alphas.bin.gz", 23206004, 31561787, "ea49da91490cd9b9a8fa11e9a15997d0f8fafefd4b35d9fa5123028becbc6bbb"),
            TranslationModelFile(Role.VOCAB, "vocab.enta.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enta.spm.gz", 449763, 1097357, "f298bd508aea203450897907cafe1238c5e917721864f361ae7038adafff57af"),
        )),
    ),
    TranslationLanguage(
        "te",
        TranslationDirection("te", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.teen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.teen.s2t.bin.gz", 2209444, 4815756, "4b2e7a95965f9a666a99cf1e913fb752452e5626b51f0dc46392cdd57491c210"),
            TranslationModelFile(Role.MODEL, "model.teen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.teen.intgemm.alphas.bin.gz", 13202063, 17141051, "78bbbf7d48277a0c8d05f04828a2c1c0b863f24cd743032c9ecd0a663d62f53c"),
            TranslationModelFile(Role.VOCAB, "vocab.teen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.teen.spm.gz", 448555, 1056197, "ec8090b2c966058b1e1efc7dc951dd7c0ccfb66b1efc0dcfb1f4063b7a89e9d0"),
        )),
        TranslationDirection("en", "te", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.ente.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.ente.s2t.bin.gz", 1434105, 2832156, "63eea185036a52cd43b70537ac3526a93dd8d04c7904daeffcf4a00d60f2ed6e"),
            TranslationModelFile(Role.MODEL, "model.ente.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.ente.intgemm.alphas.bin.gz", 12590862, 17141051, "975698af4c7810bdac720590fa6c1fc9dee57c6b68c7bca535314e8bb5d96754"),
            TranslationModelFile(Role.VOCAB, "vocab.ente.spm", "$TRANSLATION_MODELS_RELEASE/vocab.ente.spm.gz", 448838, 1056424, "1048434654e9a22eb960ad738650ecd2b989a5699bb7621f2a275698642c480d"),
        )),
    ),
    TranslationLanguage(
        "th",
        TranslationDirection("th", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.then.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.then.s2t.bin.gz", 2239323, 4487056, "5208d8211cedf98618b096e53367034e6a58862713afc6037e47405a0b3dcb4a"),
            TranslationModelFile(Role.MODEL, "model.then.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.then.intgemm.alphas.bin.gz", 22974117, 31561787, "16b0406382e6f0f2602fea63c517519173b647ea93fb130dcfe221f94cbc3126"),
            TranslationModelFile(Role.VOCAB, "vocab.then.spm", "$TRANSLATION_MODELS_RELEASE/vocab.then.spm.gz", 451231, 995429, "75744883f180dbe53b5298e1b7bc3b24083ce1a3dfa54911306347f96bb897c6"),
        )),
        TranslationDirection("en", "th", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enth.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enth.s2t.bin.gz", 1601933, 3016612, "ae7b432685ed724d9f663e0b5b8fe834982597c679fb6f5afb2045d60cbd1d19"),
            TranslationModelFile(Role.MODEL, "model.enth.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enth.intgemm.alphas.bin.gz", 22976729, 31561787, "8e736bcca5844f977ee1ee653167e17bbc73d94e50bad18108335dba0b8b9837"),
            TranslationModelFile(Role.VOCAB, "vocab.enth.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enth.spm.gz", 450379, 993517, "afa8d8be186df4c9b4acb684d9473e2dfd9f33e4f12b862fcef8cec34d323ecd"),
        )),
    ),
    TranslationLanguage(
        "tr",
        TranslationDirection("tr", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.tren.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.tren.s2t.bin.gz", 2470683, 4662492, "e06304247fc4dfd55fcab21bfc9656a28f81fcf8efb2ccb0a5796b296bfeac1b"),
            TranslationModelFile(Role.MODEL, "model.tren.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.tren.intgemm.alphas.bin.gz", 12362908, 17140836, "0939c2d12325a2f80a92d3c3ddaf718510837d03ee59303aa963b179368ec68a"),
            TranslationModelFile(Role.VOCAB, "vocab.tren.spm", "$TRANSLATION_MODELS_RELEASE/vocab.tren.spm.gz", 409060, 811353, "dfa22c3d15a6bdfb7765edc9e42c77daff8597a9ebe088fe886094ff0baeaef1"),
        )),
        TranslationDirection("en", "tr", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.entr.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.entr.s2t.bin.gz", 1546258, 3261300, "cf74d4edec0b51affd30a43e6bd2c2274bf4ce7fd54c24fd293db2c5c4bf043d"),
            TranslationModelFile(Role.MODEL, "model.entr.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.entr.intgemm.alphas.bin.gz", 13159314, 17141051, "52d10136b1a4804879989aa9ee146e83ced75aa0ce2d371b4e582473ed6b9020"),
            TranslationModelFile(Role.VOCAB, "vocab.entr.spm", "$TRANSLATION_MODELS_RELEASE/vocab.entr.spm.gz", 395473, 798793, "01e55973e65a34c5efbdce3968857d4e53998b4bef131c5125a19f8e44d8f87c"),
        )),
    ),
    TranslationLanguage(
        "uk",
        TranslationDirection("uk", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.uken.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.uken.s2t.bin.gz", 1790588, 3914120, "86af22d2c43268f87fc5b5ba32485d25defceba5ed38195b27e6c25c44c07ab9"),
            TranslationModelFile(Role.MODEL, "model.uken.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.uken.intgemm.alphas.bin.gz", 12677432, 17141051, "7cbdd1d664b22e757320ba47f79c7f658d3a581383e1f73868fce83b3fcad3d1"),
            TranslationModelFile(Role.VOCAB, "vocab.uken.spm", "$TRANSLATION_MODELS_RELEASE/vocab.uken.spm.gz", 415266, 886410, "7dbbba94effd24a118ade251686c0cea991217c29123362b36f56ea5f2de6362"),
        )),
        TranslationDirection("en", "uk", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enuk.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enuk.s2t.bin.gz", 1564122, 3054364, "0c368488f43c5165c341b5112a02e42a1fabcc7bd0103d56262da025a9b3196f"),
            TranslationModelFile(Role.MODEL, "model.enuk.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enuk.intgemm.alphas.bin.gz", 22864374, 31561787, "a832a434ce97764c285dd9f7c193d0c283b80a61bf93fbafdcb8a6bd02273e12"),
            TranslationModelFile(Role.VOCAB, "vocab.enuk.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enuk.spm.gz", 436850, 922077, "3e8e291d2c09f9ef98bace26e8092269807bbdad69f367d9a11b5c7c2cc009bb"),
        )),
    ),
    TranslationLanguage(
        "ur",
        TranslationDirection("ur", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.uren.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.uren.s2t.bin.gz", 1833159, 3518528, "77c4db97cbeb355e17048e9bb2fa58fc9da51d426b63c764d28eee28a2aae10c"),
            TranslationModelFile(Role.MODEL, "model.uren.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.uren.intgemm.alphas.bin.gz", 22876447, 31561787, "dfde841519ac46727898d96db8653d1815144febb89e6ba507d421090939e026"),
            TranslationModelFile(Role.VOCAB, "vocab.uren.spm", "$TRANSLATION_MODELS_RELEASE/vocab.uren.spm.gz", 418061, 843115, "a032fc0676566befe0cd7b1f4d56a52c13a716fd5ebad5f41b49c5e4c3796bc4"),
        )),
        TranslationDirection("en", "ur", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enur.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enur.s2t.bin.gz", 1498625, 3067772, "5b41a291b3e8bf5ea216a99c2e47d583427b16f6a3d173fdc1a4ff4b6f46efc8"),
            TranslationModelFile(Role.MODEL, "model.enur.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enur.intgemm.alphas.bin.gz", 22684591, 31561787, "6cfe125daa21fcb9b3b602152fd4961ef47e609a9272ef14b788c1be2bd4435d"),
            TranslationModelFile(Role.VOCAB, "vocab.enur.spm", "$TRANSLATION_MODELS_RELEASE/vocab.enur.spm.gz", 417745, 842549, "7d3a5e2f33c1e6959beadb7e31427046d13f588a7becbcb51f54bc1ea31862a1"),
        )),
    ),
    TranslationLanguage(
        "vi",
        TranslationDirection("vi", "en", "tiny", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.vien.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.vien.s2t.bin.gz", 1887658, 3910184, "46a1a63af1fc0828e34ee23a2b2bc3daecf8ea30681a1b21dcb2461c61d1076f"),
            TranslationModelFile(Role.MODEL, "model.vien.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.vien.intgemm.alphas.bin.gz", 12914609, 17141051, "30239a051e58cbc0f8e256b46b9234a2a59b714bb09c091897f92786942e9861"),
            TranslationModelFile(Role.VOCAB, "vocab.vien.spm", "$TRANSLATION_MODELS_RELEASE/vocab.vien.spm.gz", 375643, 757250, "cb532c07aeeb22e22f1319b0cff91659e7e8a8bbfd67b18f1eb513d277368474"),
        )),
        TranslationDirection("en", "vi", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.envi.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.envi.s2t.bin.gz", 2246027, 4597684, "12e8809c89d33dd1052c1619733d84fb7be9f49e5e72102e71fcf9f13c47737a"),
            TranslationModelFile(Role.MODEL, "model.envi.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.envi.intgemm.alphas.bin.gz", 24244705, 31561787, "0c0c339e218ca55ee577e4f0f800ba5bd0ad57f76ac940978e95663cf36bbe4a"),
            TranslationModelFile(Role.VOCAB, "vocab.envi.spm", "$TRANSLATION_MODELS_RELEASE/vocab.envi.spm.gz", 400183, 785200, "497f3de63d59fd9f89bafc5e215e5cc8a308981f49a94de813c8fd0490885e25"),
        )),
    ),
    TranslationLanguage(
        "zh",
        TranslationDirection("zh", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.zhen.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.zhen.s2t.bin.gz", 4822158, 9219192, "216b4f87e61c89741114fa36b3cf01fb1e3a32cf0eb97bf1cb2f992951e8691b"),
            TranslationModelFile(Role.MODEL, "model.zhen.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.zhen.intgemm.alphas.bin.gz", 32726806, 43977787, "c430e24baad44b8e4f725458e2454aec8a760faefbd0a4592c80f114b051f692"),
            TranslationModelFile(Role.VOCAB, "vocab.zhen.spm", "$TRANSLATION_MODELS_RELEASE/vocab.zhen.spm.gz", 738862, 1359697, "244ac04cd4e2126852fc6f697b2aa1e04acad4492c5ec8b37453974f33f88183"),
        )),
        TranslationDirection("en", "zh", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enzh.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enzh.s2t.bin.gz", 2536039, 4485184, "806f75821c0b838f4a8f4afe5bab3db8289cb7e5187753ba04c3bceadd75687a"),
            TranslationModelFile(Role.MODEL, "model.enzh.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enzh.intgemm.alphas.bin.gz", 33375922, 43849787, "7f255403b3bb2502f08ac4d5ca397a8a5a13f899d2f2e987a4934e089d241d16"),
            TranslationModelFile(Role.SOURCE_VOCAB, "srcvocab.enzh.spm", "$TRANSLATION_MODELS_RELEASE/srcvocab.enzh.spm.gz", 407784, 806952, "7846e3c236388390f4e5d321f8413d67f34c1bab5f066165eeb673bfd07607cc"),
            TranslationModelFile(Role.TARGET_VOCAB, "trgvocab.enzh.spm", "$TRANSLATION_MODELS_RELEASE/trgvocab.enzh.spm.gz", 425748, 772004, "4d641ce165b1f8478ee2ffb5149d2d46fab3779dc8fa1e9b97f9af1d2206c091"),
        )),
    ),
    TranslationLanguage(
        "zh_hant",
        TranslationDirection("zh_hant", "en", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.zh_hanten.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.zh_hanten.s2t.bin.gz", 3268812, 6385944, "69046bfea1a70a556b5669be3c014958698683ef3c3f00b8dfd5c6b4e8f4f8ca"),
            TranslationModelFile(Role.MODEL, "model.zh_hanten.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.zh_hanten.intgemm.alphas.bin.gz", 33653648, 43849787, "07af851b5a9160e84f3327e6f6151725e2712bed7b6b86edde5920fae107e55b"),
            TranslationModelFile(Role.SOURCE_VOCAB, "srcvocab.zh_hanten.spm", "$TRANSLATION_MODELS_RELEASE/srcvocab.zh_hanten.spm.gz", 423691, 769669, "e28a5484fce525e13a6cde4737b2fac08cb3c9cc60c13da9a6395c38833f7936"),
            TranslationModelFile(Role.TARGET_VOCAB, "trgvocab.zh_hanten.spm", "$TRANSLATION_MODELS_RELEASE/trgvocab.zh_hanten.spm.gz", 408143, 812572, "071d675ee1a1b5faffbde94910814998f187df9717b007ae56d54d0a6ae791ac"),
        )),
        TranslationDirection("en", "zh_hant", "base-memory", listOf(
            TranslationModelFile(Role.SHORTLIST, "lex.50.50.enzh_hant.s2t.bin", "$TRANSLATION_MODELS_RELEASE/lex.50.50.enzh_hant.s2t.bin.gz", 2290215, 4057188, "b254c97043a9ba5ff2791abac8b411dc024de6257576745a522ccc6c92421870"),
            TranslationModelFile(Role.MODEL, "model.enzh_hant.intgemm.alphas.bin", "$TRANSLATION_MODELS_RELEASE/model.enzh_hant.intgemm.alphas.bin.gz", 33291007, 43849787, "79cb710e5e66bb0490368bf158f42aff800a0f9ef2f6449d98dfb654f2d02669"),
            TranslationModelFile(Role.SOURCE_VOCAB, "srcvocab.enzh_hant.spm", "$TRANSLATION_MODELS_RELEASE/srcvocab.enzh_hant.spm.gz", 404976, 803694, "5ad55cf62d3e8b0a1cefacc0086b1ceb26d0df6415205714effa76bbb1a3063b"),
            TranslationModelFile(Role.TARGET_VOCAB, "trgvocab.enzh_hant.spm", "$TRANSLATION_MODELS_RELEASE/trgvocab.enzh_hant.spm.gz", 416659, 751671, "324622c18601da5784569eeda74b77e5ae96b164657eb8029a9dabfdcd29803b"),
        )),
    ),
)
